/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rank destinations by forecast weather
         * @description Discovers every named destination of the requested type inside the polygon, unions in any `custom_destinations`, fetches a real hourly forecast for each, and returns the top `limit` ranked by `sort_by`.
         *
         *     Discovery is never sampled, so cost scales with how many destinations the polygon contains, not with `limit`. A large polygon over dense terrain can take tens of seconds. For a progress feed instead of a single long wait, use `POST /api/analyze/stream`.
         */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rank destinations, streaming progress as it goes
         * @description Identical analysis to `POST /api/analyze`, delivered as Server-Sent Events so a caller can show progress instead of waiting on one long request.
         *
         *     Check the status code first, then the stream. A request that fails validation is rejected with **422 before the stream opens**, exactly as on `POST /api/analyze`. Once the stream does open the status is **200 for the rest of the exchange**, including for failures, because the connection is already streaming by the time an upstream problem surfaces. So a 200 here means the request was accepted, not that the analysis succeeded. Four event types arrive as `data:` lines carrying a JSON object with a `type` field:
         *
         *     - `status` — a human-readable phase message in `message`, plus an optional `detail` line for mid-phase news: a fall-over to a backup map server, or a weather-quota pace wait with its resume estimate
         *     - `progress` — `processed`, `total`, and `percent` counters
         *     - `keepalive` — periodic no-op during quiet stretches (a paced analysis can wait most of a minute for quota); ignore it
         *     - `result` — the terminal success event, carrying a full `AnalyzeResponse` in `data`
         *     - `error` — the terminal failure event, with the reason in `message` and the same machine-readable `error` object (`code`, `retryable`) the JSON routes answer with; an over-limit refusal also carries the `AnalysisRefusal` remedy fields, and an upstream rate limit carries `scope` and `retry_after_s`
         *
         *     Exactly one `result` or one `error` ends the stream.
         *
         *     Rate limiting applies before the stream opens: a client past the per-address limit gets a plain **429 with `Retry-After`**, exactly as on `POST /api/analyze`. Capacity problems found mid-analysis (the instance-wide upstream budget saturating) arrive as an `error` event, since the stream is already open.
         */
        post: operations["analyze_stream_api_analyze_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Describe supported features and enforced limits
         * @description Everything a client needs to build a valid request without hardcoding constants or scraping the docs. Every value is read from the same constants the validators enforce, so this can never drift from actual behavior.
         */
        get: operations["capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report deployment-specific UI configuration */
        get: operations["config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover and resolve destinations without forecasts
         * @description The discovery half of `POST /api/analyze` on its own: every named destination of the requested type inside the polygon, with no forecasts attached. Discovery is never sampled, and the same candidate ceiling applies, so a list that would refuse there refuses identically here.
         *
         *     It also *resolves* `custom_destinations`, matching each caller-supplied coordinate to the nearest OSM peak to fill in the elevation and OSM id that a bare coordinate pair cannot carry. Send a custom list alone (with an empty `destination_types`) to resolve without discovering anything, or alongside a polygon to get both in one call.
         *
         *     This exists so a browser client can fetch forecasts itself, spending its own Open-Meteo quota instead of this deployment's — which is exactly what the bundled web app does. If you are building a client and want ranked forecasts in one call, `POST /api/analyze` remains the endpoint for that.
         */
        post: operations["destinations_api_destinations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up a place by name
         * @description Thin proxy to Nominatim, forwarding its JSON verbatim. The response shape is therefore Nominatim's `jsonv2` format, not something Bluebird Forecast defines, and each row carries `lat`, `lon`, `display_name`, and `extratags` (which is where a summit's `ele` lives).
         *
         *     This exists because Nominatim's usage policy asks callers to identify themselves with a real User-Agent, which a browser fetch cannot set. That same policy forbids autocomplete, so call this on an explicit search action rather than on every keystroke.
         */
        get: operations["geocode_api_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/smoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Smoke plumes from NOAA's Hazard Mapping System
         * @description Today's hand-traced smoke plumes covering North America, at all three densities.
         *
         *     HMS is an analyst product, not a model: people at NOAA read GOES imagery and trace what they can see, roughly twice a day. So this is a picture of where the smoke is rather than a forecast, and there is nothing here to animate.
         *
         *     The whole analysis comes back in one response and there is no bounding box to send: a busy day measured under half a megabyte, so filtering would cost a parameter and save nothing.
         *
         *     This instance fetches the dated file from NOAA on a timer and serves it to everyone, and serves it past its refresh deadline when NOAA is unreachable — smoke traced this morning is the only tracing there will be until the next pass. Read `fetched_at` and `analysis_date` to see how current the answer is. Only an instance that has never completed a fetch answers 503.
         *
         *     Coverage is North America, which is what HMS analyzes. An empty result elsewhere means "not covered", not "clear air".
         */
        get: operations["smoke_api_smoke_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the running build
         * @description Answers what release is actually live, without cross-referencing the GitHub release, the Docker Hub tag, and the manifests repo. Preview builds report `pr-<number>`. Local and Docker Compose builds report `dev` for every field, because nothing baked a real identity in.
         */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wildfires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active US wildfire perimeters in a bounding box
         * @description Active wildfire perimeters from NIFC's WFIGS "Interagency Perimeters — Current" layer, intersecting `bbox`.
         *
         *     This exists because NIFC's ArcGIS quota belongs to *their* organization and is shared by every consumer of the public dataset, so a browser calling NIFC directly competes with the rest of the internet for it and loses at random. This instance fetches the national set on a timer and serves it to everyone, which reduces Bluebird Forecast's contribution to that quota to a fixed handful of requests per hour no matter how many people are looking at maps.
         *
         *     Coverage is the United States only: NIFC does not publish perimeters elsewhere, so an empty result outside the US means "not covered", not "nothing burning".
         *
         *     Perimeters are served past their refresh deadline when NIFC is unreachable, because a shape measured an hour ago still answers a 10-mile proximity question correctly. Read `fetched_at` to see how current the answer is. Only an instance that has never completed a fetch answers 503.
         */
        get: operations["wildfires_api_wildfires_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisRefusal
         * @description 400 body for a request that parsed but cannot run as asked.
         *
         *     `detail` is always present and readable on its own, exactly like
         *     `ErrorResponse`. The structured fields appear only on over-limit
         *     refusals, so a client can offer working remedies (prefill an elevation
         *     floor, offer an explicit top-N analysis) instead of a dead retry button.
         */
        AnalysisRefusal: {
            /**
             * Detail
             * @description Plain-language refusal, shown to an end user unmodified.
             */
            detail: string;
            /** @description The machine-readable half of the same refusal. */
            error: components["schemas"]["ApiErrorInfo"];
            /**
             * Found
             * @description How many candidates the search actually found.
             */
            found?: number | null;
            /**
             * Limit
             * @description The analysis ceiling the count exceeded (destinations).
             */
            limit?: number | null;
            /**
             * Suggested Keeps
             * @description How many candidates would remain with the suggested floor applied (unknown elevations always pass elevation filters, so this can be well under the limit).
             */
            suggested_keeps?: number | null;
            /**
             * Suggested Min Elevation Ft
             * @description A computed elevation floor that would bring the candidate count under the limit, when one exists. Rounded up to a clean number.
             */
            suggested_min_elevation_ft?: number | null;
        };
        /**
         * AnalyzeRequest
         * @description One analysis: which destinations, over which window, ranked how.
         * @example {
         *       "destination_types": [
         *         "peak"
         *       ],
         *       "forecast_mode": "current",
         *       "limit": 5,
         *       "polygon": {
         *         "coordinates": [
         *           [
         *             [
         *               -122.03,
         *               47.44
         *             ],
         *             [
         *               -121.91,
         *               47.44
         *             ],
         *             [
         *               -121.91,
         *               47.53
         *             ],
         *             [
         *               -122.03,
         *               47.53
         *             ],
         *             [
         *               -122.03,
         *               47.44
         *             ]
         *           ]
         *         ],
         *         "type": "Polygon"
         *       },
         *       "sort_by": "precip_total_in",
         *       "sort_desc": false
         *     }
         */
        AnalyzeRequest: {
            /**
             * Custom Destinations
             * @description Your own destinations, merged into whatever the polygon discovers. A custom row matching a discovered one by name or by coordinates to five decimals replaces it.
             */
            custom_destinations?: components["schemas"]["CustomDestination"][] | null;
            /**
             * Destination Types
             * @description What to discover inside the polygon, as a set — several types are found in one Overpass query rather than one request each, so asking for peaks and lakes together costs what peaks alone would. Order is irrelevant and duplicates are ignored.
             *
             *     Empty means discover nothing, which is how a request analyzes only its `custom_destinations`. `custom` is not a discoverable type and is rejected here. `GET /api/capabilities` lists the types this deployment actually supports.
             */
            destination_types?: components["schemas"]["DestinationType"][];
            /**
             * End Datetime
             * @description ISO 8601, inclusive of the hour it lands in. Required for `window`, and rejected for the other two modes.
             */
            end_datetime?: string | null;
            /**
             * @description Which of the three forecast modes this request is. `current` needs no timestamps and analyzes the hour at hand. `at` takes `start_datetime` alone and samples that single hour, past or future. `window` takes both and analyzes the span.
             *
             *     Omitting it is supported for compatibility and inferred from what you send: both timestamps means `window`, neither means `current`. Sending only `start_datetime` without a mode is rejected, because it could equally mean `at` or a `window` missing its end.
             */
            forecast_mode?: components["schemas"]["ForecastMode"] | null;
            /**
             * @description Which weather model answers. Models disagree, sometimes by more than the thing being measured: at one Cascades summit over three days, ECMWF and GFS both totalled 0.000 in of precipitation while ICON gave 0.004 in.
             *
             *     Each model also reaches a different distance ahead, so this bounds `end_datetime` as well: hours past the chosen model's horizon come back null rather than failing, and `GET /api/capabilities` publishes how far each one reaches. `gfs_hrrr` is the short-range outlier — roughly two days, against two weeks for the global models — and is also the only regional one, covering the continental US with parts of Canada and Mexico and refusing any point outside that grid.
             * @default gfs_seamless
             */
            forecast_model?: components["schemas"]["ForecastModel"];
            /**
             * Include Series
             * @description Send each row's hourly `series`. The hours are the bulk of the body, by an order of magnitude on a long window, so a caller that reads only the aggregates should set this false.
             *
             *     Nothing else changes. The aggregates are computed from the same hours either way, `times` is still sent, and air quality is still fetched and summarized under the same best-effort terms. True by default, so an existing caller sees the shape it always saw.
             * @default true
             */
            include_series?: boolean;
            /**
             * Include Unnamed Peaks
             * @description Also discover summits OSM knows only by their height, named after it (`Peak 5961`). Off by default because it is not a small addition: measured over one 8x10 km box in the Alpine Lakes, 7 peaks are named and 13 are not, so this roughly triples the candidate count — every candidate being a weighted upstream call and a step closer to the analysis ceiling. Ignored unless `peak` is among `destination_types`.
             * @default false
             */
            include_unnamed_peaks?: boolean;
            /**
             * Limit
             * @description How many ranked rows to return. Discovery is never sampled, so this trims the response, not the work: every candidate is forecast and ranked before the cut.
             * @default 10
             */
            limit?: number;
            /**
             * Max Aqi
             * @description Drop rows whose `aqi_max` is above this. A row with a null `aqi_max` passes either bound rather than being dropped: air quality is only forecast about five days out and the fetch is best-effort, so a missing number is an absence of evidence, not evidence of bad air. Setting either bound also makes the analysis fetch air quality for every candidate instead of only the returned rows, since a bound cannot be applied to a value that was never fetched.
             */
            max_aqi?: number | null;
            /**
             * Max Elevation Ft
             * @description Drop candidates above this elevation.
             */
            max_elevation_ft?: number | null;
            /**
             * Max Freeze Ft
             * @description Drop rows whose `freeze_max_ft` is above this, i.e. keep only destinations whose freezing level never rose above it during the window. A row with a null `freeze_max_ft` passes either bound: only some forecast models publish a freezing level at all, so a missing number says which model answered rather than what the weather did, and dropping those rows would empty the whole result under every other model.
             */
            max_freeze_ft?: number | null;
            /**
             * Max Precip Total In
             * @description Drop rows whose `precip_total_in` is above this.
             */
            max_precip_total_in?: number | null;
            /**
             * Max Snow Depth In
             * @description Drop rows whose `snow_depth_in` is above this. Nulls pass, under the same terms.
             */
            max_snow_depth_in?: number | null;
            /**
             * Max Temp F
             * @description Drop rows whose `temp_max_f` is above this, i.e. keep only destinations that stay at or below it for the whole window.
             */
            max_temp_f?: number | null;
            /**
             * Max Wind Mph
             * @description Drop rows whose `wind_max_mph` is above this, i.e. keep only destinations that never exceed it during the window.
             */
            max_wind_mph?: number | null;
            /**
             * Min Aqi
             * @description Drop rows whose `aqi_max` is below this.
             */
            min_aqi?: number | null;
            /**
             * Min Elevation Ft
             * @description Drop candidates below this elevation. Candidates with an unknown elevation always pass through rather than being silently dropped.
             */
            min_elevation_ft?: number | null;
            /**
             * Min Freeze Ft
             * @description Drop rows whose `freeze_min_ft` is below this, i.e. keep only destinations whose freezing level never fell below it during the window. Not bounded below: a freezing level of 0 is a reading, not a gap.
             */
            min_freeze_ft?: number | null;
            /**
             * Min Precip Total In
             * @description Drop rows whose `precip_total_in` is below this.
             */
            min_precip_total_in?: number | null;
            /**
             * Min Snow Depth In
             * @description Drop rows whose `snow_depth_in` is below this. A row with a null `snow_depth_in` passes either bound: the destination is outside the snow grid, or this instance holds no grid, and neither says anything about how much snow is on the ground.
             */
            min_snow_depth_in?: number | null;
            /**
             * Min Temp F
             * @description Drop rows whose `temp_min_f` is below this, i.e. keep only destinations that stay at or above it for the whole window. Not bounded below: a floor of -40 is a real request.
             */
            min_temp_f?: number | null;
            /**
             * Min Wind Mph
             * @description Drop rows whose `wind_min_mph` is below this.
             */
            min_wind_mph?: number | null;
            /** @description Search area for destination discovery. Required whenever `destination_types` is non-empty; with no types requested discovery is skipped entirely and only `custom_destinations` are analyzed. */
            polygon?: components["schemas"]["GeoPolygon"] | null;
            /**
             * @description Metric the ranking sorts on.
             * @default precip_total_in
             */
            sort_by?: components["schemas"]["SortBy"];
            /**
             * Sort Desc
             * @description Sort direction. False ranks lowest first, which is the useful default: driest, calmest, coldest, cleanest. True flips it to wettest, windiest, warmest, smokiest.
             * @default false
             */
            sort_desc?: boolean;
            /**
             * Start Datetime
             * @description ISO 8601; a naive timestamp is read as UTC. Required for `at` and `window`, and rejected for `current`.
             */
            start_datetime?: string | null;
            /**
             * Top By Elevation
             * @description Explicit opt-in for an over-limit candidate set: instead of refusing, keep the highest-elevation candidates up to the analysis limit (rows with unknown elevation are dropped first, since they cannot claim to be among the highest). The response then reports `truncated: true` and the pre-cut count in `total_found`, so a partial ranking is never silent. Off by default: an unasked-for cut would misrepresent the ranking.
             * @default false
             */
            top_by_elevation?: boolean;
        };
        /**
         * AnalyzeResponse
         * @description A completed analysis: the ranking, and what it was drawn from.
         */
        AnalyzeResponse: {
            /**
             * Error
             * @description Always null here. A failed analysis returns a 4xx or 5xx with a `detail` message instead. The field exists because the streaming endpoint reuses this shape.
             */
            error?: string | null;
            /**
             * Results
             * @description Ranked destinations, best first, at most `limit` of them.
             */
            results: components["schemas"]["DestinationResult"][];
            /**
             * Snow Analysis Date
             * @description The date of the SNODAS analysis behind every `snow_depth_in` on this response, as `YYYY-MM-DD`. Null when this instance holds no grid, which is also when every row's `snow_depth_in` is null.
             */
            snow_analysis_date?: string | null;
            /**
             * Times
             * @description Shared hourly grid for every row's `series`, as epoch milliseconds UTC. Sent once because it is identical across destinations for a given window, and sent in both shapes: under `include_series: false` it is the only statement of which hours the aggregates reduced.
             * @default []
             */
            times?: number[];
            /**
             * Total Found
             * @description Pre-truncation candidate count when `truncated` is true; null otherwise. Lets a client caption an elected top-N honestly ("top 1,500 of 2,340").
             */
            total_found?: number | null;
            /**
             * Total Matched
             * @description How many of those candidates satisfied the request's forecast bounds, before `limit` cut the list. Equal to `total_queried` when no bound was set, so a client can always say "N of M matching" without knowing whether the caller filtered. It is a separate number because a bound drops rows the caller paid to fetch, and `total_queried` keeps meaning what it always has: how much was analyzed.
             */
            total_matched: number;
            /**
             * Total Queried
             * @description How many candidates were forecast and ranked before `limit` cut the list. Compare against `len(results)` to see how much of the ranking is not being shown.
             */
            total_queried: number;
            /**
             * Truncated
             * @description True only when the request set `top_by_elevation` and the candidate set exceeded the limit, so only the highest candidates were analyzed. Never true otherwise: an over-limit set without the opt-in refuses with a 400 instead.
             * @default false
             */
            truncated?: boolean;
        };
        /**
         * ApiErrorInfo
         * @description The same failure as a code a program can branch on.
         *
         *     It rides beside `detail` rather than replacing it, because the two are
         *     read by different audiences: the sentence by a person, the code by a
         *     client deciding whether to retry.
         */
        ApiErrorInfo: {
            /** @description Which kind of failure this is, from a closed vocabulary. Stable contract: unlike `detail`, a code is not reworded. */
            code: components["schemas"]["ErrorCode"];
            /**
             * Retryable
             * @description Whether sending the identical request again is worth trying. False means only the caller can change the outcome. On a 429 or 503 the `Retry-After` header says when.
             */
            retryable: boolean;
        };
        /**
         * CapabilitiesResponse
         * @description What this deployment can do, and the bounds it enforces.
         */
        CapabilitiesResponse: {
            /**
             * Api Key Header
             * @description The request header that carries an Open-Meteo API key on the analyze routes. The public deployment requires it there and forwards the key to Open-Meteo, so the request spends the caller's quota.
             */
            api_key_header: string;
            /** Data Sources */
            data_sources: components["schemas"]["DataSource"][];
            /**
             * Destination Types
             * @description Destination types this deployment can discover, and exactly the values a request may send in `destination_types`. Narrower than the `DestinationType` enum, which also models types that are not yet discoverable, and `custom`, which names rows the caller supplies in `custom_destinations` rather than something to go and find.
             */
            destination_types: string[];
            /**
             * Forecast Models
             * @description Accepted values for `forecast_model`, best first. Models disagree with each other, so which one answered is part of what a number means.
             *
             *     The order is this deployment's editorial ranking for mountain terrain, not a sort on any field below — grid spacing over complex terrain is weighted above forecast length, so it is roughly the reverse of ordering by `forecast_hours`. Render it as given.
             */
            forecast_models: components["schemas"]["ForecastModelInfo"][];
            limits: components["schemas"]["Limits"];
            /**
             * Sort Keys
             * @description Accepted values for `sort_by`, usable with `sort_desc`.
             */
            sort_keys: string[];
        };
        /**
         * ConfigResponse
         * @description Runtime configuration the SPA reads on load.
         *
         *     Deployment-specific, and not part of the analysis contract. For build
         *     identity use `GET /api/version`; for the limits requests are validated
         *     against use `GET /api/capabilities`.
         */
        ConfigResponse: {
            preview: components["schemas"]["PreviewConfig"];
        };
        /**
         * CustomDestination
         * @description A caller-supplied destination, analyzed alongside discovered ones.
         */
        CustomDestination: {
            /**
             * Elevation Ft
             * @description Elevation in feet. Optional, but supplying it is what lets the row take part in an elevation-band filter: rows with an unknown elevation are never filtered out.
             */
            elevation_ft?: number | null;
            /**
             * Latitude
             * @description Latitude in decimal degrees, -90 to 90.
             */
            latitude: number;
            /**
             * Longitude
             * @description Longitude in decimal degrees, -180 to 180.
             */
            longitude: number;
            /**
             * Name
             * @description Display name, 1 to 255 characters.
             */
            name: string;
        };
        /**
         * DataSource
         * @description One upstream Bluebird Forecast depends on.
         */
        DataSource: {
            /** Name */
            name: string;
            /** Provides */
            provides: string;
            /** Url */
            url: string;
        };
        /**
         * DestinationResult
         * @description One ranked destination, summarized over the analyzed window.
         */
        DestinationResult: {
            /**
             * Aqi Avg
             * @description Mean US AQI across the window, all EPA pollutants combined. Null past the air-quality horizon, or if the best-effort fetch failed. An air-quality outage never fails an analysis.
             */
            aqi_avg?: number | null;
            /**
             * Aqi Max
             * @description Worst single AQI hour. Null under the same terms.
             */
            aqi_max?: number | null;
            /**
             * Aqi Min
             * @description Cleanest single AQI hour. Null under the same terms.
             */
            aqi_min?: number | null;
            /**
             * Elevation Ft
             * @description Elevation in feet, when known.
             */
            elevation_ft?: number | null;
            /**
             * Freeze Avg Ft
             * @description Mean freezing level across the window. Null under the same terms.
             */
            freeze_avg_ft?: number | null;
            /**
             * Freeze Max Ft
             * @description Highest freezing level in the window. Null under the same terms.
             */
            freeze_max_ft?: number | null;
            /**
             * Freeze Min Ft
             * @description Lowest freezing level in the window, feet above sea level. Read against `elevation_ft`: below the destination, the whole destination was below freezing at that hour. Zero means the freezing level reached sea level, not that there is no value. Null for every hour of a forecast model that does not publish the variable, which is five of the eight; an absent freezing level never affects the other figures on this row.
             */
            freeze_min_ft?: number | null;
            /**
             * Latitude
             * @description Latitude in decimal degrees.
             */
            latitude: number;
            /**
             * Longitude
             * @description Longitude in decimal degrees.
             */
            longitude: number;
            /**
             * Name
             * @description Destination name, from OSM or your CSV.
             */
            name: string;
            /**
             * Osm Id
             * @description OpenStreetMap identifier such as `node/12345`. Null for custom destinations, which have no OSM identity.
             */
            osm_id?: string | null;
            /**
             * Precip Avg In Hr
             * @description Mean hourly precipitation, inches.
             */
            precip_avg_in_hr: number;
            /**
             * Precip Max In Hr
             * @description Wettest single hour in the window, inches.
             */
            precip_max_in_hr: number;
            /**
             * Precip Min In Hr
             * @description Driest single hour in the window, inches. Zero for any window with one dry hour.
             */
            precip_min_in_hr: number;
            /**
             * Precip Total In
             * @description Total precipitation across the window, inches.
             */
            precip_total_in: number;
            /** @description Hourly detail behind the summary figures above, aligned to `times`. Null when the upstream forecast carried no hours inside the window, and on every row when the request set `include_series: false`. */
            series?: components["schemas"]["HourlySeries"] | null;
            /**
             * Snow Depth In
             * @description Snow on the ground today, in inches, from the NOHRSC SNODAS 1 km grid. One number per destination that ignores the analyzed window entirely: it is the current analysis rather than a forecast, so it has no minimum, mean or maximum and no hourly series. Null outside the grid, which covers the contiguous United States and southern Canada, and null while this instance holds no grid. Over permanent ice SNODAS accumulates year over year, so a glaciated summit reads over a thousand inches; that is ice rather than this season's snow.
             */
            snow_depth_in?: number | null;
            /**
             * Temp Avg F
             * @description Mean temperature, degrees Fahrenheit.
             */
            temp_avg_f: number;
            /**
             * Temp Max F
             * @description Warmest hour, degrees Fahrenheit.
             */
            temp_max_f: number;
            /**
             * Temp Min F
             * @description Coldest hour, degrees Fahrenheit.
             */
            temp_min_f: number;
            /**
             * Type
             * @description Where the row came from: the discovery type, or `custom` for a caller-supplied destination.
             */
            type: string;
            /**
             * Wind Avg Mph
             * @description Mean wind speed at the destination's elevation, miles per hour. Each hour interpolates Open-Meteo's free-air wind between the two pressure levels bracketing `elevation_ft`, floored at the 10 m surface wind; rows with no elevation, or below the lowest level (~762 m), report the 10 m wind. All three wind aggregates reduce the same adjusted hourly values.
             */
            wind_avg_mph: number;
            /**
             * Wind Max Mph
             * @description Windiest hour, miles per hour.
             */
            wind_max_mph: number;
            /**
             * Wind Min Mph
             * @description Calmest hour, miles per hour.
             */
            wind_min_mph: number;
        };
        /**
         * DestinationType
         * @enum {string}
         */
        DestinationType: "peak" | "trailhead" | "lake" | "custom";
        /**
         * DestinationsRequest
         * @description Discovery only: which destinations exist, with no forecasts attached.
         *
         *     This is the first half of `POST /api/analyze`. The SPA uses it to get the
         *     candidate list and then fetches Open-Meteo itself, so a browser analysis
         *     costs this deployment one Overpass query instead of dozens of forecast
         *     calls.
         *
         *     Two kinds of candidate arrive here. A polygon is *discovered*; a
         *     `custom_destinations` list is *resolved* — the caller already knows where
         *     its points are, so the only open question is what OSM knows about them.
         */
        DestinationsRequest: {
            /**
             * Custom Destinations
             * @description Caller-supplied destinations to resolve against OSM. Each is matched to the nearest peak within ~150 m, filling in `elevation_ft` and `osm_id` where OSM knows them — a point with no match keeps whatever it arrived with. A row that already carries an elevation is never looked up or overwritten.
             *
             *     Resolution is best-effort: if the map service is unreachable the rows come back exactly as sent rather than failing the request.
             */
            custom_destinations?: components["schemas"]["CustomDestination"][] | null;
            /**
             * Destination Types
             * @description What to discover inside the polygon, as a set — several types come back from one Overpass query, each row tagged with the type it actually is. Order is irrelevant and duplicates are ignored.
             *
             *     Empty means a resolve-only request: discovery is skipped and only `custom_destinations` come back. `custom` is not a discoverable type and is rejected here.
             */
            destination_types?: components["schemas"]["DestinationType"][];
            /**
             * Include Unnamed Peaks
             * @description Also discover summits OSM knows only by their height, named after it (`Peak 5961`). Off by default because it is not a small addition: measured over one 8x10 km box in the Alpine Lakes, 7 peaks are named and 13 are not, so this roughly triples the candidate count — every candidate being a weighted upstream call and a step closer to the analysis ceiling. Ignored unless `peak` is among `destination_types`.
             * @default false
             */
            include_unnamed_peaks?: boolean;
            /**
             * Max Elevation Ft
             * @description Drop candidates above this elevation.
             */
            max_elevation_ft?: number | null;
            /**
             * Min Elevation Ft
             * @description Drop candidates below this elevation. Candidates with an unknown elevation always pass through rather than being silently dropped.
             */
            min_elevation_ft?: number | null;
            /** @description Search area, validated exactly as on `POST /api/analyze`. Required unless `custom_destinations` is supplied; send both to resolve a caller's list alongside a discovery. */
            polygon?: components["schemas"]["GeoPolygon"] | null;
            /**
             * Top By Elevation
             * @description Explicit opt-in for an over-limit result: keep the highest-elevation candidates up to the analysis limit instead of refusing (unknown elevations are dropped first). The response reports `truncated: true` and the pre-cut count in `total_found`.
             * @default false
             */
            top_by_elevation?: boolean;
        };
        /**
         * DestinationsResponse
         * @description Everything found, after the optional elevation band.
         */
        DestinationsResponse: {
            /**
             * Destinations
             * @description Every named match inside the polygon, never sampled, plus any resolved `custom_destinations`. Order is OSM's with the caller's own rows last, not a ranking; ranking is the caller's job once forecasts are attached.
             */
            destinations: components["schemas"]["DiscoveredDestination"][];
            /**
             * Snow Analysis Date
             * @description The date of the SNODAS analysis behind every `snow_depth_in` on this response, as `YYYY-MM-DD`. Null when this instance holds no grid, which is also when every row's `snow_depth_in` is null.
             */
            snow_analysis_date?: string | null;
            /**
             * Total
             * @description Same as `len(destinations)`, for convenience.
             */
            total: number;
            /**
             * Total Found
             * @description Pre-truncation candidate count when `truncated` is true; null otherwise.
             */
            total_found?: number | null;
            /**
             * Truncated
             * @description True only when the request set `top_by_elevation` and the found set exceeded the limit, so `destinations` holds the highest candidates only.
             * @default false
             */
            truncated?: boolean;
        };
        /**
         * DiscoveredDestination
         * @description One candidate, forecast-free.
         */
        DiscoveredDestination: {
            /**
             * Elevation Ft
             * @description Elevation in feet, when OSM knows it. For a custom row this is the caller's own value if one was sent, otherwise the matched peak's — null when neither exists.
             */
            elevation_ft?: number | null;
            /**
             * Latitude
             * @description Latitude in decimal degrees.
             */
            latitude: number;
            /**
             * Longitude
             * @description Longitude in decimal degrees.
             */
            longitude: number;
            /**
             * Name
             * @description Destination name: OSM's for a discovered row, the caller's for a custom one.
             */
            name: string;
            /**
             * Osm Id
             * @description OpenStreetMap identifier such as `node/12345`.
             */
            osm_id?: string | null;
            /**
             * Snow Depth In
             * @description Snow on the ground today, in inches, from the NOHRSC SNODAS 1 km grid. One number per destination that ignores the analyzed window entirely: it is the current analysis rather than a forecast, so it has no minimum, mean or maximum and no hourly series. Null outside the grid, which covers the contiguous United States and southern Canada, and null while this instance holds no grid. Over permanent ice SNODAS accumulates year over year, so a glaciated summit reads over a thousand inches; that is ice rather than this season's snow.
             */
            snow_depth_in?: number | null;
            /**
             * Type
             * @description The discovery type this row matched, or `custom` for a caller-supplied row.
             */
            type: string;
        };
        /**
         * ErrorCode
         * @description Why a request failed, in the caller's vocabulary rather than the implementation's.
         * @enum {string}
         */
        ErrorCode: "validation" | "refusal" | "model_coverage" | "invalid_api_key" | "not_found" | "method_not_allowed" | "rate_limited" | "upstream_rate_limited" | "upstream_unavailable" | "busy" | "snapshot_unavailable" | "internal";
        /**
         * ErrorResponse
         * @description Body of a hand-raised API error.
         *
         *     Note that a 422 differs: request validation is Pydantic's, and its `detail`
         *     is a list of per-field objects rather than a string. That shape is
         *     documented separately as `HTTPValidationError`.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Plain-language explanation of what went wrong, written to be shown to an end user unmodified.
             */
            detail: string;
            /** @description The machine-readable half of the same failure. */
            error: components["schemas"]["ApiErrorInfo"];
        };
        /**
         * ForecastMode
         * @enum {string}
         */
        ForecastMode: "current" | "at" | "window";
        /**
         * ForecastModel
         * @description The weather model Open-Meteo is asked for, as its own `models=` value.
         *
         *     Declared best-first for this app's terrain (see `MODEL_INFO`), and that
         *     order is the contract: `/api/capabilities` publishes it as declared and the
         *     picker renders it as published.
         *
         *     Four ids Open-Meteo serves are deliberately absent, each for its own
         *     reason (all probed 2026-08-01):
         *
         *     - `best_match` is its blend, which picks per location and never reports its
         *       pick — the whole reason this enum exists.
         *     - `ecmwf_aifs025` returned an hourly array of nothing but nulls at three
         *       points on three continents.
         *     - `metno_seamless` and `knmi_seamless` are byte-identical to each other
         *       everywhere in North America (Rainier, Whitney and Denali, all three
         *       variables), so offering both offered one dataset twice — and the survivor
         *       matched no `ecmwf_*` or `gem_*` product either, while KNMI's own
         *       `knmi_harmonie_arome_europe` refuses coordinates outside Europe. Neither
         *       is offered: this list is ranked best-first, and a model whose North
         *       American provenance cannot be established has no defensible place in it.
         * @enum {string}
         */
        ForecastModel: "gfs_seamless" | "gem_seamless" | "ecmwf_ifs025" | "gfs_hrrr" | "ukmo_seamless" | "icon_seamless" | "jma_seamless" | "meteofrance_seamless";
        /**
         * ForecastModelInfo
         * @description One selectable weather model, and how far it reaches.
         */
        ForecastModelInfo: {
            /**
             * Blend
             * @description True for a model that serves a fine regional grid for the first day or two and a coarse global one after that, so one series changes model partway along. Published rather than left to be read off the `_seamless` suffix, which is a naming habit rather than a contract: this flag is the only reliable way to tell a blended product from a single-model one.
             */
            blend: boolean;
            /**
             * Default
             * @description True for the model used when `forecast_model` is omitted.
             */
            default: boolean;
            /**
             * Finest Grid Km
             * @description The finest grid this model offers anywhere, in kilometres. For the `*_seamless` blends that is their regional component, not their global one, so it describes the model at its best rather than everywhere: where the fine grid lands is in `summary`.
             */
            finest_grid_km: number;
            /**
             * Forecast Hours
             * @description How many hours ahead of now this model still has data for, as a floor. Distinct from `limits.max_future_days`, which is the hard edge the API refuses past: within that edge, a model simply stops, returning nulls for hours beyond its own reach rather than an error. A model's usable lead shrinks as its last run ages and jumps back when the next lands, so this sits under the trough rather than on any single reading.
             */
            forecast_hours: number;
            /**
             * Id
             * @description Value to send as `forecast_model`.
             */
            id: string;
            /**
             * Label
             * @description Human-readable name, as the picker shows it.
             */
            label: string;
            /**
             * Regional
             * @description True for a model run over part of the world rather than all of it. A request naming one is rejected with 400 if any destination falls outside its grid — including destinations the caller never sees, since discovery happens server-side.
             */
            regional: boolean;
            /**
             * Summary
             * @description Why to choose this model, written for someone planning a trip rather than for a meteorologist: what it is best at, then what it blends in. Most entries fold a fine regional grid into a coarse global one for roughly two days, which is why `finest_grid_km` and `forecast_hours` do not describe the same moment. The blend clause names only what is added, never the headline model, since several labels are named after one of their own parts. No model here blends across agencies.
             */
            summary: string;
        };
        /**
         * GeoPolygon
         * @description A GeoJSON Polygon bounding the search area.
         */
        GeoPolygon: {
            /**
             * Coordinates
             * @description GeoJSON coordinate rings. Only the outer ring is read. Positions are `[longitude, latitude]`, which is GeoJSON order and the reverse of how coordinates are usually spoken. The ring should close by repeating its first position.
             */
            coordinates: number[][][];
            /**
             * Type
             * @constant
             */
            type: "Polygon";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HourlySeries
         * @description Per-hour values, aligned index-for-index to `AnalyzeResponse.times`.
         *
         *     A null is a genuine gap, meaning no value at that hour, most often AQI past
         *     its shorter horizon. Consumers should render a break rather than
         *     interpolating across one.
         */
        HourlySeries: {
            /**
             * Aqi
             * @description US AQI, all EPA pollutants combined.
             */
            aqi: (number | null)[];
            /**
             * Freeze Ft
             * @description Freezing level, feet above sea level. Null at every hour for the models that do not publish the variable; see `freeze_avg_ft` on the result.
             */
            freeze_ft: (number | null)[];
            /**
             * Precip In
             * @description Precipitation, inches.
             */
            precip_in: (number | null)[];
            /**
             * Temp F
             * @description Temperature, degrees Fahrenheit.
             */
            temp_f: (number | null)[];
            /**
             * Wind Mph
             * @description Wind speed at the destination's elevation, miles per hour. See `wind_avg_mph` on the result for how it is derived.
             */
            wind_mph: (number | null)[];
        };
        /**
         * Limits
         * @description Hard bounds every request is validated against.
         */
        Limits: {
            /**
             * Aqi Forecast Days
             * @description How far ahead air quality is available. The underlying CAMS model runs far shorter than the weather forecast, so `aqi_avg` and `aqi_max` come back null for hours past this horizon. An analysis never fails because of it.
             */
            aqi_forecast_days: number;
            /**
             * Archive Days
             * @description How far back `start_datetime` may reach and still be answered with real numbers, through the archive endpoint. A deployment choice rather than a limit of the data, which runs decades deeper; the calendar in the app offers exactly this reach.
             */
            archive_days: number;
            /**
             * Max Destinations
             * @description Ceiling on candidates in a single analysis, counting discovered and custom destinations together. Every candidate gets a real forecast, so this is what bounds upstream cost. Exceeding it fails loudly rather than silently truncating the ranking.
             */
            max_destinations: number;
            /**
             * Max Future Days
             * @description How far ahead `end_datetime` may reach. The weather API forecasts roughly 16 days; this bound carries the same slack.
             */
            max_future_days: number;
            /**
             * Max Limit
             * @description Largest accepted `limit`.
             */
            max_limit: number;
            /**
             * Max Past Days
             * @description How far back `start_datetime` may reach. The archive endpoint serves the history past `past_data_days`; this bound is `archive_days` plus slack, so a legitimate edge window is never falsely rejected.
             */
            max_past_days: number;
            /**
             * Max Polygon Area Km2
             * @description Largest drawable search area, measured as a bounding-box approximation of the polygon. Larger areas are rejected with 422.
             */
            max_polygon_area_km2: number;
            /**
             * Min Limit
             * @description Smallest accepted `limit`.
             */
            min_limit: number;
            /**
             * Past Data Days
             * @description Where the forecast endpoint's own data ends, and therefore the boundary between the two weather endpoints. A window older than this is answered from the archive instead, which changes what a row can carry: the archive names no model and reports wind at 10 m rather than at the destination's elevation. A window that starts older than this and ends inside it is served by both endpoints, joined at this boundary.
             */
            past_data_days: number;
            /** @description Per-client request pacing. Unlike the bounds above, exceeding these is not a request error: the same request succeeds once `Retry-After` has elapsed. */
            rate: components["schemas"]["RateLimits"];
        };
        /**
         * PreviewConfig
         * @description Preview-environment banner state.
         */
        PreviewConfig: {
            /**
             * Commit
             * @description Commit this preview was built from. Null unless enabled.
             */
            commit: string | null;
            /**
             * Enabled
             * @description Whether this deployment is a PR preview rather than production.
             */
            enabled: boolean;
            /**
             * Pr
             * @description Pull request number this preview was built from. Null unless enabled.
             */
            pr: string | null;
        };
        /**
         * RateLimits
         * @description Per-client request pacing on the expensive endpoints.
         *
         *     Enforced per backend instance, so behind a multi-replica deployment the
         *     effective ceiling is roughly the number shown times the replica count.
         *     Requests past a limit receive 429 with a `Retry-After` header.
         */
        RateLimits: {
            /**
             * Analyze Burst
             * @description How many analyze requests an idle client can send back-to-back before the per-minute pace applies.
             */
            analyze_burst: number;
            /**
             * Analyze Per Minute
             * @description Sustained `POST /api/analyze` + `/api/analyze/stream` requests allowed per client address per minute (the two share one bucket). 0 means the limit is disabled.
             */
            analyze_per_minute: number;
            /**
             * Destinations Burst
             * @description How many destinations requests an idle client can send back-to-back before the per-minute pace applies.
             */
            destinations_burst: number;
            /**
             * Destinations Per Minute
             * @description Sustained `POST /api/destinations` requests per client address per minute. Its own bucket: discovery is one map query with no forecasts, so it does not spend the analyze budget. 0 means the limit is disabled.
             */
            destinations_per_minute: number;
            /**
             * Geocode Burst
             * @description How many geocode requests an idle client can send back-to-back before the per-minute pace applies.
             */
            geocode_burst: number;
            /**
             * Geocode Per Minute
             * @description Sustained `GET /api/geocode` requests per client address per minute. 0 means the limit is disabled.
             */
            geocode_per_minute: number;
            /**
             * Smoke Burst
             * @description How many smoke requests an idle client can send back-to-back before the per-minute pace applies.
             */
            smoke_burst: number;
            /**
             * Smoke Per Minute
             * @description Sustained `GET /api/smoke` requests per client address per minute. As loose as the wildfire bucket and for the same reason: it answers from a snapshot this instance already holds and reaches no upstream. 0 means the limit is disabled.
             */
            smoke_per_minute: number;
            /**
             * Wildfires Burst
             * @description How many wildfire requests an idle client can send back-to-back before the per-minute pace applies. Sized for a map pan, which refetches on a 400 ms debounce.
             */
            wildfires_burst: number;
            /**
             * Wildfires Per Minute
             * @description Sustained `GET /api/wildfires` requests per client address per minute. Among the loosest buckets, because it answers from a snapshot this instance already holds and reaches no upstream. 0 means the limit is disabled.
             */
            wildfires_per_minute: number;
        };
        /**
         * SmokeCollection
         * @description A GeoJSON FeatureCollection, plus when and for which day it was analyzed.
         *
         *     Declared for the schema only: the handler returns pre-serialized text, since
         *     every caller gets the same whole-country answer and re-encoding it per
         *     request would be work with no question behind it.
         */
        SmokeCollection: {
            /**
             * Analysis Date
             * @description The day whose analysis this is, as `YYYY-MM-DD` in US Eastern time. HMS publishes one dated file per day and its first pass lands around late morning Eastern, so before then this is yesterday's date and the plumes are yesterday's plumes. Read it rather than assuming today.
             */
            analysis_date: string;
            /**
             * Features
             * @description Smoke plumes as `Polygon` features. `density` is `Light`, `Medium` or `Heavy`; `satellite` names the GOES platform the analyst read; `observed_start` and `observed_end` bound the imagery the plume was traced from, in epoch milliseconds, and are null when HMS did not state them. A plume whose style HMS has not published before is returned as `Light` with the unrecognized value in `density_raw`.
             */
            features: {
                [key: string]: unknown;
            }[];
            /**
             * Fetched At
             * @description When this instance last fetched from NOAA, in epoch milliseconds. A GeoJSON foreign member, which map libraries ignore. Plumes are cached per instance and served past their refresh deadline when NOAA is unreachable, so this is the only honest statement of how current the shapes are.
             */
            fetched_at: number;
            /**
             * Type
             * @description Always `FeatureCollection`, so the body drops straight into a map library.
             * @constant
             */
            type: "FeatureCollection";
        };
        /**
         * SortBy
         * @enum {string}
         */
        SortBy: "precip_total_in" | "precip_avg_in_hr" | "precip_min_in_hr" | "precip_max_in_hr" | "wind_min_mph" | "wind_avg_mph" | "wind_max_mph" | "temp_min_f" | "temp_avg_f" | "temp_max_f" | "freeze_min_ft" | "freeze_avg_ft" | "freeze_max_ft" | "aqi_avg" | "aqi_min" | "aqi_max" | "snow_depth_in";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponse
         * @description Build identity of the running service.
         */
        VersionResponse: {
            /**
             * Built At
             * @description ISO 8601 UTC timestamp of the image build, or "dev".
             * @example 2026-07-27T18:42:11Z
             */
            built_at: string;
            /**
             * Commit
             * @description Git SHA the image was built from, or "dev".
             * @example bce6660f1a2b3c4d5e6f708192a3b4c5d6e7f809
             */
            commit: string;
            /**
             * Version
             * @description Semantic version of the running release, or "dev".
             * @example 0.28.0
             */
            version: string;
        };
        /**
         * WildfireCollection
         * @description A GeoJSON FeatureCollection, plus when Bluebird Forecast last heard from NIFC.
         *
         *     Declared for the schema only: the handler returns pre-serialized text so a
         *     viewport is a filter and a join rather than a re-encode of every perimeter.
         */
        WildfireCollection: {
            /**
             * Coverage
             * @description The area WFIGS covers, as a GeoJSON MultiPolygon geometry riding as a second foreign member: a coarse (±50 km, biased outward) outline of the United States, with Alaska split at the antimeridian so no ring wraps 180°. An empty `features` array for a bbox outside this geometry means the dataset cannot see that area, not that nothing is burning there. Static per release.
             */
            coverage: {
                [key: string]: unknown;
            };
            /**
             * Features
             * @description Active wildfire perimeters intersecting the requested bounding box, as NIFC's WFIGS layer returned them. Properties carry the incident name, acreage, containment percentage, and timestamps; `attr_` fields come from the joined IRWIN record and `poly_` fields from the perimeter polygon, so either may be null and callers should coalesce the pair.
             */
            features: {
                [key: string]: unknown;
            }[];
            /**
             * Fetched At
             * @description When this instance last fetched perimeters from NIFC, in epoch milliseconds. A GeoJSON foreign member, which map libraries ignore. Perimeters are cached per instance and served past their refresh deadline when NIFC is unreachable, so this is the only honest statement of how current the shapes are. It is not when any individual fire was last surveyed: that is the per-feature `attr_ModifiedOnDateTime_dt`, which routinely runs days older.
             */
            fetched_at: number;
            /**
             * Type
             * @description Always `FeatureCollection`, so the body drops straight into a map library.
             * @constant
             */
            type: "FeatureCollection";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description The request parsed but does not describe a runnable analysis: the window is inverted, the destination type is not discoverable, `custom_destinations` is missing for a custom analysis, the elevation band excludes every candidate, or the candidate count exceeds the cap. Over-cap refusals carry the structured remedy fields (`found`, `limit`, and a computed elevation-floor suggestion when one exists); send `top_by_elevation: true` to elect an explicit top-N analysis instead. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRefusal"];
                };
            };
            /** @description Open-Meteo rejected the API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Either this client is analyzing faster than the per-address limit (shared with `POST /api/analyze/stream`), or the upstream weather service rate-limited this deployment mid-analysis. `Retry-After` says how many seconds to wait in both cases. `GET /api/capabilities` publishes the per-address limit. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An upstream failed: every Overpass mirror was unreachable, or the weather API did not answer. Transient and worth retrying. Air quality is exempt, since a failure there degrades to null rather than failing the analysis. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description This instance's upstream budget is saturated: too many analyses already have calls in flight to the shared free APIs. Transient by nature; `Retry-After` says when a retry is worthwhile. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyze_stream_api_analyze_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description An SSE stream. Ends with either a `result` or an `error` event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Open-Meteo rejected the API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description This client is analyzing faster than the per-address limit. `Retry-After` says how many seconds to wait. `GET /api/capabilities` publishes the limit. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    destinations_api_destinations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DestinationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationsResponse"];
                };
            };
            /** @description The request parsed but describes nothing to do: neither a polygon nor a custom list was sent, no types were requested and there is no list to resolve, a requested type is not yet implemented, or the polygon contains more candidates than the analysis ceiling. Over-cap refusals carry the structured remedy fields; send `top_by_elevation: true` to elect an explicit top-N result instead. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRefusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description This client is discovering faster than the per-address limit (its own bucket, independent of the analyze endpoints). `Retry-After` says how many seconds to wait. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Every Overpass mirror failed. Transient and worth retrying. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description This instance's Overpass budget stayed saturated too long. Transient; `Retry-After` says when a retry is worthwhile. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    geocode_api_geocode_get: {
        parameters: {
            query: {
                /** @description Place name to search for, such as `Mount Rainier`. */
                q: string;
                /** @description Maximum places to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching places, in Nominatim's `jsonv2` format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description This client is searching faster than the per-address limit. `Retry-After` says how many seconds to wait. `GET /api/capabilities` publishes the limit. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Nominatim was unreachable or returned an unexpected payload. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description This instance is already at Nominatim's usage-policy pace and the queue is full. Transient; `Retry-After` says when to retry. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    smoke_api_smoke_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every plume in the current analysis, with its date. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmokeCollection"];
                };
            };
            /** @description This client is requesting faster than the per-address limit. `Retry-After` says how many seconds to wait. `GET /api/capabilities` publishes the limit. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description This instance has never completed a fetch from NOAA, so it has nothing to serve, not even stale. Transient; `Retry-After` says when to retry. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    wildfires_api_wildfires_get: {
        parameters: {
            query: {
                /** @description Bounding box as `west,south,east,north` in decimal degrees (EPSG:4326). A perimeter is returned when its own bounding box overlaps this one. */
                bbox: string;
                /** @description Geometry fidelity. `coarse` simplifies perimeters to roughly 56 metres, which is far finer than a map pixel at any zoom that shows a whole fire and about a thirteenth of the bytes. `full` returns them as surveyed, for callers measuring distances rather than drawing shapes. */
                detail?: "coarse" | "full";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perimeters intersecting the box, with the fetch timestamp. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WildfireCollection"];
                };
            };
            /** @description `bbox` was missing, malformed, or outside valid coordinate ranges. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description This client is requesting faster than the per-address limit. `Retry-After` says how many seconds to wait. `GET /api/capabilities` publishes the limit. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description This instance has never completed a fetch from NIFC, so it has nothing to serve, not even stale. Transient; `Retry-After` says when to retry. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
