import { describe, expect, it } from 'vitest'
import pkg from '../package.json'

// The two rules the generated schema lives under, neither of which a type can
// state about itself. api-compat.ts holds the assertions between the schema and
// the hand-written types; these hold the setup those assertions sit in.
//
// Sources are read as text through the `?raw` trick styles.test.ts and
// branding.test.ts use, so nothing here executes a module.
const sources = import.meta.glob('./**/*.{ts,tsx}', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

// Spelled in pieces so this file's own text is not one of the matches.
const VALUE_IMPORT = new RegExp(`(?<!import type )\\{[^}]*\\}\\s*from\\s*'[./]*api` + `-schema'`)

describe('the generated API schema', () => {
  // The issue's second acceptance criterion is "no new runtime dependency", and
  // the `.d.ts` output is how that is enforced rather than promised: a
  // declaration file emits nothing, so it cannot be imported as a value at all.
  // This catches the near miss instead — a value import that reads fine today
  // and that a later edit could reach for at runtime.
  it('is only ever imported for its types', () => {
    const offenders = Object.entries(sources)
      .filter(([path]) => !path.endsWith('api-compat.test.ts'))
      .filter(([, text]) => VALUE_IMPORT.test(text))
      .map(([path]) => path)
    expect(offenders, 'import the schema with `import type`').toEqual([])
  })

  // The generator is pinned the way ruff is pinned in pr.yml: a version that
  // moves on its own can rewrite the file with no contract change behind it,
  // and the CI drift check would then fail a PR that changed nothing. One pin,
  // in one string, with the check script deriving its command from the generate
  // script rather than repeating it.
  it('is generated by one pinned command', () => {
    const scripts = pkg.scripts as Record<string, string>
    expect(scripts['generate:api']).toMatch(/openapi-typescript@\d+\.\d+\.\d+\s/)
    expect(scripts['check:api']).toBe('npm run generate:api -- --check')
  })
})
