import { afterEach, describe, expect, it, vi } from 'vitest'
import {
  ARCHIVE_URL,
  FORECAST_URL,
  OpenMeteoHttpError,
  OpenMeteoModelCoverage,
  OpenMeteoRateLimited,
  OpenMeteoUnreachable,
  aqiMetrics,
  aqiSeries,
  callWeight,
  fetchAqi,
  fetchSpans,
  fetchWeather,
  parseTs,
  resetOpenMeteoState,
  roundHalfEven,
  weatherMetrics,
  weatherSeries,
} from './openMeteo'
import { archiveBoundaryMs, windowSource } from './forecastWindow'
import vectors from './weather_vectors.json'

// ── The shared-vector contract ─────────────────────────────────────────────
// weather_vectors.json is generated by the backend reference implementation
// (backend/scripts/generate_weather_vectors.py) and CI diffs this copy
// against the backend's. These tests are the frontend half of the contract:
// the TypeScript port must reproduce every expectation byte-for-byte.

type VectorCase = {
  name: string
  window: { start: string; end: string }
  payload: never
  elevation_ft?: number
  expected_metrics: unknown
  expected_series: unknown
}

function windowMs(c: VectorCase): [number, number] {
  return [parseTs(c.window.start)!, parseTs(c.window.end)!]
}

describe('weather vectors', () => {
  for (const c of vectors.weather as unknown as VectorCase[]) {
    it(c.name, () => {
      const [startMs, endMs] = windowMs(c)
      const elevationFt = c.elevation_ft ?? null
      expect(weatherMetrics(c.payload, startMs, endMs, elevationFt)).toEqual(
        c.expected_metrics,
      )
      expect(weatherSeries(c.payload, startMs, endMs, elevationFt)).toEqual(
        c.expected_series,
      )
    })
  }
})

describe('aqi vectors', () => {
  for (const c of vectors.aqi as unknown as VectorCase[]) {
    it(c.name, () => {
      const [startMs, endMs] = windowMs(c)
      expect(aqiMetrics(c.payload, startMs, endMs)).toEqual(c.expected_metrics)
      expect(aqiSeries(c.payload, startMs, endMs)).toEqual(c.expected_series)
    })
  }
})

// ── Parity primitives ──────────────────────────────────────────────────────

describe('roundHalfEven', () => {
  it('rounds halves to the even neighbor, like Python round()', () => {
    expect(roundHalfEven(80.5, 0)).toBe(80)
    expect(roundHalfEven(81.5, 0)).toBe(82)
    expect(roundHalfEven(50.25, 1)).toBe(50.2)
    expect(roundHalfEven(50.75, 1)).toBe(50.8)
    expect(roundHalfEven(0.03125, 4)).toBe(0.0312)
  })

  it('rounds non-halves normally', () => {
    expect(roundHalfEven(1.24, 1)).toBe(1.2)
    expect(roundHalfEven(1.26, 1)).toBe(1.3)
  })
})

describe('parseTs', () => {
  it('reads naive Open-Meteo stamps as UTC, never local time', () => {
    // Without the Z re-stamp, environments west of UTC would shift this by
    // the local offset — the exact trap the port exists to avoid.
    expect(parseTs('2026-07-21T00:00')).toBe(Date.parse('2026-07-21T00:00:00Z'))
  })

  it('degrades garbage to null like the backend parser', () => {
    expect(parseTs('not-a-time')).toBeNull()
    expect(parseTs(42)).toBeNull()
  })
})

// ── Fetch orchestration ────────────────────────────────────────────────────

const WINDOW = {
  startMs: Date.parse('2026-07-21T00:00:00Z'),
  endMs: Date.parse('2026-07-21T02:00:00Z'),
}

function hourlyPayload() {
  return {
    hourly: {
      time: ['2026-07-21T00:00', '2026-07-21T01:00'],
      precipitation: [0.1, 0.2],
      temperature_2m: [50.0, 52.0],
      wind_speed_10m: [5.0, 7.0],
    },
  }
}

function jsonResponse(body: unknown): Response {
  return { ok: true, status: 200, json: async () => body } as unknown as Response
}

afterEach(() => {
  vi.unstubAllGlobals()
  // Module-level state (per-location cache, pacer buckets) must not let one
  // test's successful fetch answer the next test from cache.
  resetOpenMeteoState()
})

// Every fetch names a model now; these tests are not about which one, so they
// all use the default. `models=` reaching the wire is asserted on its own below.
const MODEL = 'ecmwf_ifs025'

// The clock, pinned. WINDOW is a fixed date, so a real `Date.now()` would put it
// on the forecast side of the archive boundary today and on the archive side a
// few days from now (#123) — the endpoint under test would change with the wall
// calendar. `nowMs` is the only thing here that reads the clock.
const NOW_MS = Date.parse('2026-07-21T12:00:00Z')
const OPTS = { model: MODEL, nowMs: NOW_MS }

describe('fetchWeather', () => {
  it('normalizes the single-location object payload to one result', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse(hourlyPayload())))
    const out = await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9 }],
      WINDOW.startMs,
      WINDOW.endMs, OPTS,
    )
    expect(out).toHaveLength(1)
    expect(out[0]?.precip_total_in).toBe(0.3)
    expect(out[0]?.series?.times).toHaveLength(2)
  })

  it('serves an identical repeat from the cache without refetching', async () => {
    const fetchSpy = vi.fn(async () => jsonResponse(hourlyPayload()))
    vi.stubGlobal('fetch', fetchSpy)
    const coords = [{ latitude: 47.5, longitude: -121.9 }]
    await fetchWeather(coords, WINDOW.startMs, WINDOW.endMs, OPTS)
    const again = await fetchWeather(coords, WINDOW.startMs, WINDOW.endMs, OPTS)
    expect(fetchSpy).toHaveBeenCalledTimes(1)
    expect(again[0]?.precip_total_in).toBe(0.3)
  })

  it('requests the five level winds alongside the surface variables', async () => {
    const fetchSpy = vi.fn(async () => jsonResponse(hourlyPayload()))
    vi.stubGlobal('fetch', fetchSpy)
    await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9 }],
      WINDOW.startMs,
      WINDOW.endMs, OPTS,
    )
    const url = new URL(String((fetchSpy.mock.calls[0] as unknown[])[0]))
    const hourly = (url.searchParams.get('hourly') ?? '').split(',')
    for (const name of [
      'wind_speed_925hPa',
      'wind_speed_850hPa',
      'wind_speed_700hPa',
      'wind_speed_600hPa',
      'wind_speed_500hPa',
    ]) {
      expect(hourly).toContain(name)
    }
    // Nine variables stay at weight factor 1: max(1, vars x models/10)
    // with one model.
    expect(hourly).toHaveLength(9)
  })

  it('asks only for the hours the window needs (#212)', async () => {
    // The request used to name whole calendar days and the aggregation threw
    // the overhang away, in the visitor's own memory. Both bounds floor to the
    // hour, which cannot drop a stamp the inclusive filter keeps.
    const fetchSpy = vi.fn(async () => jsonResponse(hourlyPayload()))
    vi.stubGlobal('fetch', fetchSpy)
    await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9 }],
      Date.parse('2026-07-21T09:30:00Z'),
      Date.parse('2026-07-21T14:45:00Z'),
      OPTS,
    )
    const params = new URL(String((fetchSpy.mock.calls[0] as unknown[])[0])).searchParams
    expect(params.get('start_hour')).toBe('2026-07-21T09:00')
    expect(params.get('end_hour')).toBe('2026-07-21T14:00')
    expect(params.get('start_date')).toBeNull()
    expect(params.get('end_date')).toBeNull()
  })

  it('asks for a single hour when the window is a point sample', async () => {
    // The window every Current analysis resolves to, and the one the whole-day
    // request wasted most on: measured 2026-08-23 over 50 locations, 97.3 KB
    // for the day against 32.8 KB for the hour.
    const fetchSpy = vi.fn(async () => jsonResponse(hourlyPayload()))
    vi.stubGlobal('fetch', fetchSpy)
    const moment = Date.parse('2026-07-21T13:00:00Z')
    await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9 }],
      moment,
      moment + 60_000,
      OPTS,
    )
    const params = new URL(String((fetchSpy.mock.calls[0] as unknown[])[0])).searchParams
    expect(params.get('start_hour')).toBe('2026-07-21T13:00')
    expect(params.get('end_hour')).toBe('2026-07-21T13:00')
  })

  it('adjusts wind to the elevation the coordinate carries (#257)', async () => {
    const payload = hourlyPayload()
    Object.assign(payload.hourly, {
      wind_speed_925hPa: [7.0, 7.0],
      wind_speed_850hPa: [10.0, 10.0],
      wind_speed_700hPa: [30.0, 30.0],
      wind_speed_600hPa: [40.0, 40.0],
      wind_speed_500hPa: [50.0, 50.0],
    })
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse(payload)))
    const out = await fetchWeather(
      // 8,000 ft between 850 hPa (1457 m) and 700 hPa (3012 m):
      // 10 + 20 * (981.4 / 1555) = 22.6226... → 22.6 at every hour.
      [{ latitude: 47.5, longitude: -121.9, elevation_ft: 8000 }],
      WINDOW.startMs,
      WINDOW.endMs, OPTS,
    )
    expect(out[0]?.wind_avg_mph).toBe(22.6)
    expect(out[0]?.series?.wind_mph).toEqual([22.6, 22.6])
  })

  it('adjusts wind to the terrain elevation the response carries, when asked (#288)', async () => {
    // The forecast grid's option: a lattice point has no destination
    // elevation, but Open-Meteo reports the terrain height it resolved for
    // the coordinate, and that is real ground the sample stands on.
    const payload = hourlyPayload() as ReturnType<typeof hourlyPayload> & { elevation?: number }
    payload.elevation = 2438.4 // meters = 8,000 ft: between 850 and 700 hPa
    Object.assign(payload.hourly, {
      wind_speed_925hPa: [7.0, 7.0],
      wind_speed_850hPa: [10.0, 10.0],
      wind_speed_700hPa: [30.0, 30.0],
      wind_speed_600hPa: [40.0, 40.0],
      wind_speed_500hPa: [50.0, 50.0],
    })
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse(payload)))
    const out = await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9 }],
      WINDOW.startMs,
      WINDOW.endMs, { ...OPTS, terrainElevation: true },
    )
    // Same interpolation as a destination at 8,000 ft: 10 + 20 * (981.4/1555).
    expect(out[0]?.wind_avg_mph).toBe(22.6)

    // Without the option, the same coordinate keeps the 10 m wind — and the
    // two answers live under different cache keys, so neither poisons the
    // other at identical coordinates.
    const plain = await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9 }],
      WINDOW.startMs,
      WINDOW.endMs, OPTS,
    )
    expect(plain[0]?.wind_avg_mph).toBe(6.0) // mean of 5, 7
  })

  it('lets a claimed elevation beat the terrain option', async () => {
    // A destination's own height is more specific than the DEM's cell value.
    const payload = hourlyPayload() as ReturnType<typeof hourlyPayload> & { elevation?: number }
    payload.elevation = 500 // meters: below the lowest level, would stay 10 m
    Object.assign(payload.hourly, {
      wind_speed_925hPa: [7.0, 7.0],
      wind_speed_850hPa: [10.0, 10.0],
      wind_speed_700hPa: [30.0, 30.0],
      wind_speed_600hPa: [40.0, 40.0],
      wind_speed_500hPa: [50.0, 50.0],
    })
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse(payload)))
    const out = await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9, elevation_ft: 8000 }],
      WINDOW.startMs,
      WINDOW.endMs, { ...OPTS, terrainElevation: true },
    )
    expect(out[0]?.wind_avg_mph).toBe(22.6)
  })

  it('keys the cache by elevation, so a lattice point never reads a summit entry', async () => {
    const fetchSpy = vi.fn(async () => jsonResponse(hourlyPayload()))
    vi.stubGlobal('fetch', fetchSpy)
    await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9, elevation_ft: 8000 }],
      WINDOW.startMs,
      WINDOW.endMs, OPTS,
    )
    await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9 }],
      WINDOW.startMs,
      WINDOW.endMs, OPTS,
    )
    expect(fetchSpy).toHaveBeenCalledTimes(2)
  })

  it('classifies HTTP 429 as rate limited, never as unreachable', async () => {
    // The 2026-07-29 regression: a 429 read as "unreachable" pointed the
    // retry at a server sharing the same exhausted IP (issue #180). A
    // scope-less 429 must throw immediately, with no fallback trigger.
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({ ok: false, status: 429, json: async () => ({}) })),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs, OPTS),
    ).rejects.toBeInstanceOf(OpenMeteoRateLimited)
  })

  it('reads the tripped quota scope from the 429 body', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({
        ok: false,
        status: 429,
        json: async () => ({ error: true, reason: 'Hourly API request limit exceeded.' }),
      })),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs, OPTS),
    ).rejects.toMatchObject({ scope: 'hourly' })
  })

  // Rate limit quotas across all scopes report the same message.
  it.each([
    ['Daily API request limit exceeded.', 'daily'],
    ['Monthly API request limit exceeded.', 'monthly'],
    ['Hourly API request limit exceeded.', 'hourly'],
  ])('reports quota reached for a %s refusal', async (reason, scope) => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({ ok: false, status: 429, json: async () => ({ error: true, reason }) })),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs, OPTS),
    ).rejects.toMatchObject({
      message: 'Open-Meteo quota reached. Try again later.',
      scope,
    })
  })

  it('resumes once after a minutely 429 and completes the batch', async () => {
    vi.useFakeTimers()
    try {
      const fetchSpy = vi
        .fn()
        .mockResolvedValueOnce({
          ok: false,
          status: 429,
          headers: { get: (h: string) => (h === 'Retry-After' ? '1' : null) },
          json: async () => ({ error: true, reason: 'Minutely API request limit exceeded.' }),
        })
        .mockResolvedValueOnce(jsonResponse(hourlyPayload()))
      vi.stubGlobal('fetch', fetchSpy)
      const pending = fetchWeather(
        [{ latitude: 0, longitude: 0 }],
        WINDOW.startMs,
        WINDOW.endMs, OPTS,
      )
      await vi.advanceTimersByTimeAsync(1_100)
      const out = await pending
      expect(fetchSpy).toHaveBeenCalledTimes(2)
      expect(out[0]?.precip_total_in).toBe(0.3)
    } finally {
      vi.useRealTimers()
    }
  })

  it('classifies other HTTP statuses as an upstream error, not unreachable', async () => {
    // The server talks to the same upstream, so a 5xx must surface honestly
    // instead of triggering a doomed fallback.
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({ ok: false, status: 500, json: async () => ({}) })),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs, OPTS),
    ).rejects.toBeInstanceOf(OpenMeteoHttpError)
  })

  it('wraps network-level rejections too — the corporate-proxy case', async () => {
    // fetch rejects with a TypeError when the request never completes
    // (offline, DNS, blocked CORS). That must read as "unreachable", not
    // crash through as an unclassified error.
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new TypeError('Failed to fetch')
      }),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs, OPTS),
    ).rejects.toBeInstanceOf(OpenMeteoUnreachable)
  })

  it('lets a user cancel pass through untranslated', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new DOMException('The user aborted a request.', 'AbortError')
      }),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs, OPTS),
    ).rejects.toMatchObject({ name: 'AbortError' })
  })

  it('throws on a miscounted response instead of misaligning rows', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => jsonResponse([hourlyPayload(), hourlyPayload()])),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs, OPTS),
    ).rejects.toBeInstanceOf(OpenMeteoUnreachable)
  })

  it('reports batch progress across chunks', async () => {
    const dests = Array.from({ length: 60 }, (_, i) => ({
      latitude: i,
      longitude: i,
    }))
    vi.stubGlobal(
      'fetch',
      vi.fn(async (url: string) => {
        const count = new URL(url).searchParams.get('latitude')!.split(',').length
        return jsonResponse(Array.from({ length: count }, () => hourlyPayload()))
      }),
    )
    const seen: Array<[number, number]> = []
    await fetchWeather(dests, WINDOW.startMs, WINDOW.endMs, {
      ...OPTS,
      onProgress: (processed, total) => seen.push([processed, total]),
    })
    // Two chunks (50 + 10) completing in either order: the processed counter
    // accumulates monotonically and ends at the full total.
    expect(seen).toHaveLength(2)
    expect(seen.every(([, total]) => total === 60)).toBe(true)
    expect(seen[0][0]).toBeLessThan(seen[1][0])
    expect(seen[1][0]).toBe(60)
  })
})

// The browser path is the one most analyses take, so the model reaching the
// wire matters here as much as it does on the server.
describe('the forecast model on the browser path', () => {
  const coords = [{ latitude: 47.5, longitude: -121.9 }]

  it('names the model on every request', async () => {
    const fetchSpy = vi.fn(async (_url: string) => jsonResponse(hourlyPayload()))
    vi.stubGlobal('fetch', fetchSpy)
    await fetchWeather(coords, WINDOW.startMs, WINDOW.endMs, { ...OPTS, model: 'gfs_hrrr' })

    const url = new URL(fetchSpy.mock.calls[0][0])
    expect(url.searchParams.get('models')).toBe('gfs_hrrr')
  })

  it('does not let two models share one cache entry', async () => {
    const fetchSpy = vi.fn(async () => jsonResponse(hourlyPayload()))
    vi.stubGlobal('fetch', fetchSpy)
    await fetchWeather(coords, WINDOW.startMs, WINDOW.endMs, { ...OPTS, model: 'ecmwf_ifs025' })
    await fetchWeather(coords, WINDOW.startMs, WINDOW.endMs, { ...OPTS, model: 'gfs_seamless' })
    await fetchWeather(coords, WINDOW.startMs, WINDOW.endMs, { ...OPTS, model: 'ecmwf_ifs025' })

    // Two fetches, not three: the second model missed, the repeat of the first
    // still hit.
    expect(fetchSpy).toHaveBeenCalledTimes(2)
  })

  // Measured 2026-08-01: a batch 400s if a SINGLE one of its 50 locations is
  // outside a regional model's grid. Its own class because the remedy is
  // unlike every other failure here — not a wait, not a smaller area, but a
  // different model — and because it must never trigger the server fallback,
  // which reaches the same upstream and fails identically.
  it('classifies a regional model refusing a location as its own failure', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({
        ok: false,
        status: 400,
        clone: () => ({
          json: async () => ({ error: true, reason: 'No data is available for this location' }),
        }),
        json: async () => ({ error: true, reason: 'No data is available for this location' }),
      })),
    )
    await expect(
      fetchWeather(coords, WINDOW.startMs, WINDOW.endMs, { ...OPTS, model: 'gfs_hrrr' }),
    ).rejects.toBeInstanceOf(OpenMeteoModelCoverage)
  })

  it('leaves an ordinary 400 as an ordinary HTTP error', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({
        ok: false,
        status: 400,
        clone: () => ({ json: async () => ({ reason: 'Invalid date' }) }),
        json: async () => ({ reason: 'Invalid date' }),
      })),
    )
    await expect(
      fetchWeather(coords, WINDOW.startMs, WINDOW.endMs, { ...OPTS, model: 'gfs_hrrr' }),
    ).rejects.toBeInstanceOf(OpenMeteoHttpError)
  })
})

describe('fetchAqi', () => {
  it('degrades any failure to nulls instead of throwing', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({ ok: false, status: 500, json: async () => ({}) })),
    )
    const out = await fetchAqi(
      [{ latitude: 0, longitude: 0 }],
      WINDOW.startMs,
      WINDOW.endMs,
    )
    expect(out).toEqual([null])
  })

  it('degrades a miscounted response to nulls', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse([{}, {}])))
    const out = await fetchAqi(
      [{ latitude: 0, longitude: 0 }],
      WINDOW.startMs,
      WINDOW.endMs,
    )
    expect(out).toEqual([null])
  })

  it('skips the fetch entirely when the window starts past the horizon', async () => {
    const fetchSpy = vi.fn()
    vi.stubGlobal('fetch', fetchSpy)
    const now = Date.parse('2026-07-01T00:00:00Z')
    const out = await fetchAqi(
      [{ latitude: 0, longitude: 0 }],
      Date.parse('2026-07-20T00:00:00Z'),
      Date.parse('2026-07-21T00:00:00Z'),
      { nowMs: now },
    )
    expect(out).toEqual([null])
    expect(fetchSpy).not.toHaveBeenCalled()
  })

  it('clamps the requested end to the last hour of the ~5-day horizon', async () => {
    // The whole-day request this replaced ended at 23:00 on the cap day, so
    // the hour bound has to end there too. Clamping to the instant instead
    // would quietly drop most of a day of real AQI.
    let requested: string | null = null
    vi.stubGlobal(
      'fetch',
      vi.fn(async (url: string) => {
        requested = new URL(url).searchParams.get('end_hour')
        return jsonResponse({ hourly: { time: [], us_aqi: [] } })
      }),
    )
    const now = Date.parse('2026-07-21T00:00:00Z')
    await fetchAqi(
      [{ latitude: 0, longitude: 0 }],
      now,
      now + 15 * 86_400_000,
      { nowMs: now },
    )
    expect(requested).toBe('2026-07-26T23:00')
  })

  it('asks only for the hours the window needs (#212)', async () => {
    let params: URLSearchParams | null = null
    vi.stubGlobal(
      'fetch',
      vi.fn(async (url: string) => {
        params = new URL(url).searchParams
        return jsonResponse({ hourly: { time: [], us_aqi: [] } })
      }),
    )
    const now = Date.parse('2026-07-21T00:00:00Z')
    await fetchAqi(
      [{ latitude: 0, longitude: 0 }],
      Date.parse('2026-07-21T09:30:00Z'),
      Date.parse('2026-07-21T14:45:00Z'),
      { nowMs: now },
    )
    expect(params!.get('start_hour')).toBe('2026-07-21T09:00')
    expect(params!.get('end_hour')).toBe('2026-07-21T14:00')
    expect(params!.get('start_date')).toBeNull()
    expect(params!.get('end_date')).toBeNull()
  })
})

// ── Weighted-call accounting (mirror of backend openmeteo_weight) ──────────

describe('callWeight', () => {
  const day = (d: string) => Date.parse(`${d}T00:00:00Z`)

  it('floors to one call per location for short windows and few variables', () => {
    expect(callWeight(50, day('2026-07-29'), day('2026-07-29'), 3)).toBe(50)
  })

  it('scales by days over 14 — the full-horizon worst case', () => {
    expect(callWeight(50, day('2026-07-01'), day('2026-07-16'), 3)).toBeCloseTo(
      50 * (16 / 14),
    )
  })

  it('prices the incident shape at one call per location per endpoint', () => {
    const weather = callWeight(908, day('2026-07-29'), day('2026-08-01'), 3)
    const aqi = callWeight(908, day('2026-07-29'), day('2026-08-01'), 1)
    expect(weather + aqi).toBe(1816)
  })

  it('multiplies the variable count by the model count', () => {
    // A request naming N models returns N series per variable, so it costs
    // the same as one model with N times the variables (issue #232). The
    // browser's nine variables across three models is 27 series: factor 2.7.
    const d = day('2026-07-29')
    expect(callWeight(10, d, d, 9, 3)).toBe(callWeight(10, d, d, 27))
    expect(callWeight(10, d, d, 8, 3)).toBeCloseTo(10 * 2.4)
  })

  it('still floors three models at three variables to one call', () => {
    // The measurement behind the issue's three-model cap: 3 x 3 = 9 series is
    // under the floor, so comparing three models costs what one does.
    expect(callWeight(50, day('2026-07-29'), day('2026-07-29'), 3, 3)).toBe(50)
  })

  it.each([
    [1, 1.0],
    [2, 1.0],
    [3, 1.0],
    [4, 1.2],
    [5, 1.5],
    [8, 2.4],
  ])('prices %i models at three variables as %fx', (nModels, factor) => {
    const d = day('2026-07-29')
    expect(callWeight(100, d, d, 3, nModels)).toBeCloseTo(100 * factor)
  })

  it('defaults the model count to one and moves no existing answer', () => {
    const start = day('2026-07-29')
    const end = day('2026-08-01')
    expect(callWeight(908, start, end, 3)).toBe(callWeight(908, start, end, 3, 1))
    expect(callWeight(908, start, end, 3)).toBe(908)
  })
})


// ── The archive endpoint (issue #123) ──────────────────────────────────────
//
// A window older than the forecast endpoint's retention is answered from the
// archive instead. `windowSource` decides, mirrored with the backend, and the
// clock is pinned here so the decision is the test's rather than the calendar's.
describe('a window older than the forecast endpoint holds', () => {
  const coords = [{ latitude: 47.5, longitude: -121.9 }]
  // 200 days before NOW_MS, with a payload stamped to match.
  const ARCHIVE_WINDOW = {
    startMs: Date.parse('2026-01-02T00:00:00Z'),
    endMs: Date.parse('2026-01-02T02:00:00Z'),
  }

  function archivePayload() {
    return {
      hourly: {
        time: ['2026-01-02T00:00', '2026-01-02T01:00'],
        precipitation: [0.1, 0.2],
        temperature_2m: [30.0, 32.0],
        wind_speed_10m: [5.0, 7.0],
        // What the archive actually answers for the five levels: accepted, and
        // null at every hour (measured 2026-09-12).
        wind_speed_925hPa: [null, null],
        wind_speed_850hPa: [null, null],
        wind_speed_700hPa: [null, null],
        wind_speed_600hPa: [null, null],
        wind_speed_500hPa: [null, null],
      },
    }
  }

  it('goes to the archive endpoint and names no model', async () => {
    const fetchSpy = vi.fn(async () => jsonResponse(archivePayload()))
    vi.stubGlobal('fetch', fetchSpy)
    await fetchWeather(coords, ARCHIVE_WINDOW.startMs, ARCHIVE_WINDOW.endMs, {
      ...OPTS,
      model: 'gfs_hrrr',
    })

    const url = new URL(String((fetchSpy.mock.calls[0] as unknown[])[0]))
    expect(`${url.origin}${url.pathname}`).toBe(ARCHIVE_URL)
    // Never forwarded: the archive answers an unknown `models=` with a 200 and
    // plausible data, so a name it does not serve would be answered silently by
    // something else. Its own default is a reanalysis, one dataset everywhere.
    expect(url.searchParams.get('models')).toBeNull()
    // Everything else about the request is unchanged.
    expect(url.searchParams.get('start_hour')).toBe('2026-01-02T00:00')
    expect(url.searchParams.get('hourly')?.split(',')).toHaveLength(9)
  })

  it('keeps a recent window on the forecast endpoint', async () => {
    const fetchSpy = vi.fn(async () => jsonResponse(hourlyPayload()))
    vi.stubGlobal('fetch', fetchSpy)
    await fetchWeather(coords, WINDOW.startMs, WINDOW.endMs, OPTS)

    const url = new URL(String((fetchSpy.mock.calls[0] as unknown[])[0]))
    expect(`${url.origin}${url.pathname}`).toBe(FORECAST_URL)
    expect(url.searchParams.get('models')).toBe(MODEL)
  })

  it('does not let the two endpoints share one cache entry', async () => {
    // They answer the same coordinates from different data, and the boundary
    // between them moves with the clock, so an entry has to belong to the
    // endpoint that produced it.
    const fetchSpy = vi.fn(async () => jsonResponse(archivePayload()))
    vi.stubGlobal('fetch', fetchSpy)
    const window = [ARCHIVE_WINDOW.startMs, ARCHIVE_WINDOW.endMs] as const

    await fetchWeather(coords, ...window, OPTS)
    await fetchWeather(coords, ...window, OPTS)
    // The same window, read as a forecast window: a miss, not the archive row.
    await fetchWeather(coords, ...window, {
      ...OPTS,
      nowMs: ARCHIVE_WINDOW.startMs + 60_000,
    })

    expect(fetchSpy).toHaveBeenCalledTimes(2)
  })

  it('falls back to the 10 m wind where the levels come back null', async () => {
    const fetchSpy = vi.fn(async () => jsonResponse(archivePayload()))
    vi.stubGlobal('fetch', fetchSpy)
    const out = await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9, elevation_ft: 14_000 }],
      ARCHIVE_WINDOW.startMs,
      ARCHIVE_WINDOW.endMs,
      OPTS,
    )

    // No hour is dropped for a null level, only the wind sent back to 10 m.
    expect(out[0]?.wind_avg_mph).toBe(6)
    expect(out[0]?.wind_max_mph).toBe(7)
    expect(out[0]?.series?.wind_mph).toEqual([5, 7])
  })
})

// ── A window that crosses the boundary (issue #123) ────────────────────────
//
// Two fetches, one per endpoint, joined per location before the aggregation
// runs — so the ranking sees one series and the shared vectors stay the only
// definition of what an aggregate is.
describe('a window that crosses the archive boundary', () => {
  const coords = [{ latitude: 47.5, longitude: -121.9 }]
  // NOW_MS puts the boundary at 2026-05-27T00:00:00Z. The window has to open
  // more than a day before it to span at all: a window starting inside the last
  // local day before the seam is the forecast endpoint's whole
  // (ARCHIVE_STRADDLE_DAYS), which is the point of that tolerance.
  const SEAM_MS = Date.parse('2026-05-27T00:00:00Z')
  const SPANNING = {
    startMs: Date.parse('2026-05-25T22:00:00Z'),
    endMs: Date.parse('2026-05-27T01:00:00Z'),
  }

  function half(times: string[], precip: number[]) {
    return {
      hourly_units: { precipitation: 'inch' },
      hourly: {
        time: times,
        precipitation: precip,
        temperature_2m: times.map(() => 50.0),
        wind_speed_10m: times.map(() => 5.0),
      },
    }
  }

  const archiveHalf = () => half(['2026-05-25T22:00', '2026-05-25T23:00'], [0.1, 0.2])
  const forecastHalf = () => half(['2026-05-27T00:00', '2026-05-27T01:00'], [0.4, 0.8])

  function bothHalves() {
    const bodies = [archiveHalf(), forecastHalf()]
    return vi.fn(async () => jsonResponse(bodies.shift()))
  }

  it('classifies the window as spanning at the pinned clock', () => {
    expect(windowSource(SPANNING.startMs, SPANNING.endMs, NOW_MS)).toBe('spanning')
    expect(archiveBoundaryMs(NOW_MS)).toBe(SEAM_MS)
  })

  it('asks each endpoint for its own hours, and names the model on one', async () => {
    const fetchSpy = bothHalves()
    vi.stubGlobal('fetch', fetchSpy)
    await fetchWeather(coords, SPANNING.startMs, SPANNING.endMs, {
      ...OPTS,
      model: 'gfs_hrrr',
    })

    const urls = fetchSpy.mock.calls.map((c) => new URL(String((c as unknown[])[0])))
    expect(urls).toHaveLength(2)
    expect(`${urls[0].origin}${urls[0].pathname}`).toBe(ARCHIVE_URL)
    expect(`${urls[1].origin}${urls[1].pathname}`).toBe(FORECAST_URL)
    // Disjoint: the archive answers through the hour BEFORE the seam, because
    // both bounds are inclusive and a repeated hour would be counted twice.
    expect(urls[0].searchParams.get('start_hour')).toBe('2026-05-25T22:00')
    expect(urls[0].searchParams.get('end_hour')).toBe('2026-05-26T23:00')
    expect(urls[1].searchParams.get('start_hour')).toBe('2026-05-27T00:00')
    expect(urls[1].searchParams.get('end_hour')).toBe('2026-05-27T01:00')
    // The model rides only on the half a model answered.
    expect(urls[0].searchParams.get('models')).toBeNull()
    expect(urls[1].searchParams.get('models')).toBe('gfs_hrrr')
  })

  it('aggregates both halves as one series', async () => {
    vi.stubGlobal('fetch', bothHalves())
    const out = await fetchWeather(coords, SPANNING.startMs, SPANNING.endMs, OPTS)

    // 0.1 + 0.2 + 0.4 + 0.8: every hour of both halves, counted once.
    expect(out[0]?.precip_total_in).toBe(1.5)
    expect(out[0]?.precip_max_in_hr).toBe(0.8)
    expect(out[0]?.series?.times).toHaveLength(4)
  })

  it('drops a location whose halves disagree on units', async () => {
    // A total of inches and millimetres is a number with no meaning, so the row
    // degrades to no forecast the way every unreadable payload does.
    const bodies = [archiveHalf(), { ...forecastHalf(), hourly_units: { precipitation: 'mm' } }]
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse(bodies.shift())))
    const out = await fetchWeather(coords, SPANNING.startMs, SPANNING.endMs, OPTS)

    expect(out).toEqual([null])
  })

  it('counts a repeated hour once', async () => {
    const bodies = [archiveHalf(), half(['2026-05-25T23:00', '2026-05-27T00:00'], [9.9, 0.4])]
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse(bodies.shift())))
    const out = await fetchWeather(coords, SPANNING.startMs, SPANNING.endMs, OPTS)

    expect(out[0]?.precip_total_in).toBe(0.7) // 0.1 + 0.2 + 0.4
    expect(out[0]?.series?.times).toHaveLength(3)
  })

  it('keys the joined series apart from either half alone', async () => {
    const fetchSpy = vi.fn(async () => jsonResponse(archiveHalf()))
    vi.stubGlobal('fetch', fetchSpy)

    await fetchWeather(coords, SPANNING.startMs, SPANNING.endMs, OPTS)
    // The same coordinates and window read as one endpoint's: a miss, not the
    // joined row.
    await fetchWeather(coords, SPANNING.startMs, SPANNING.endMs, {
      ...OPTS,
      nowMs: SPANNING.startMs + 60_000,
    })
    // And the spanning fetch itself repeats from the cache.
    await fetchWeather(coords, SPANNING.startMs, SPANNING.endMs, OPTS)

    expect(fetchSpy).toHaveBeenCalledTimes(3) // two for the split, one for the half
  })

  it('prices each half on its own hours', () => {
    // Two requests are two answers, so a spanning window spends twice — and
    // pricing it on the whole window would bill the archive half's months for
    // the forecast half as well.
    const spans = fetchSpans(SPANNING.startMs, SPANNING.endMs, NOW_MS)
    expect(spans).toHaveLength(2)
    const total = spans.reduce(
      (sum, s) => sum + callWeight(50, s.startMs, s.endMs, 9, 1),
      0,
    )
    expect(total).toBe(100)
    expect(fetchSpans(WINDOW.startMs, WINDOW.endMs, NOW_MS)).toHaveLength(1)
  })
})
