import { afterEach, describe, expect, it, vi } from 'vitest'
import {
  OpenMeteoUnreachable,
  aqiMetrics,
  aqiSeries,
  fetchAqi,
  fetchWeather,
  parseTs,
  roundHalfEven,
  weatherMetrics,
  weatherSeries,
} from './openMeteo'
import vectors from './weather_vectors.json'

// ── The shared-vector contract ─────────────────────────────────────────────
// weather_vectors.json is generated by the backend reference implementation
// (backend/scripts/generate_weather_vectors.py) and CI diffs this copy
// against the backend's. These tests are the frontend half of the contract:
// the TypeScript port must reproduce every expectation byte-for-byte.

type VectorCase = {
  name: string
  window: { start: string; end: string }
  payload: never
  expected_metrics: unknown
  expected_series: unknown
}

function windowMs(c: VectorCase): [number, number] {
  return [parseTs(c.window.start)!, parseTs(c.window.end)!]
}

describe('weather vectors', () => {
  for (const c of vectors.weather as unknown as VectorCase[]) {
    it(c.name, () => {
      const [startMs, endMs] = windowMs(c)
      expect(weatherMetrics(c.payload, startMs, endMs)).toEqual(c.expected_metrics)
      expect(weatherSeries(c.payload, startMs, endMs)).toEqual(c.expected_series)
    })
  }
})

describe('aqi vectors', () => {
  for (const c of vectors.aqi as unknown as VectorCase[]) {
    it(c.name, () => {
      const [startMs, endMs] = windowMs(c)
      expect(aqiMetrics(c.payload, startMs, endMs)).toEqual(c.expected_metrics)
      expect(aqiSeries(c.payload, startMs, endMs)).toEqual(c.expected_series)
    })
  }
})

// ── Parity primitives ──────────────────────────────────────────────────────

describe('roundHalfEven', () => {
  it('rounds halves to the even neighbor, like Python round()', () => {
    expect(roundHalfEven(80.5, 0)).toBe(80)
    expect(roundHalfEven(81.5, 0)).toBe(82)
    expect(roundHalfEven(50.25, 1)).toBe(50.2)
    expect(roundHalfEven(50.75, 1)).toBe(50.8)
    expect(roundHalfEven(0.03125, 4)).toBe(0.0312)
  })

  it('rounds non-halves normally', () => {
    expect(roundHalfEven(1.24, 1)).toBe(1.2)
    expect(roundHalfEven(1.26, 1)).toBe(1.3)
  })
})

describe('parseTs', () => {
  it('reads naive Open-Meteo stamps as UTC, never local time', () => {
    // Without the Z re-stamp, environments west of UTC would shift this by
    // the local offset — the exact trap the port exists to avoid.
    expect(parseTs('2026-07-21T00:00')).toBe(Date.parse('2026-07-21T00:00:00Z'))
  })

  it('degrades garbage to null like the backend parser', () => {
    expect(parseTs('not-a-time')).toBeNull()
    expect(parseTs(42)).toBeNull()
  })
})

// ── Fetch orchestration ────────────────────────────────────────────────────

const WINDOW = {
  startMs: Date.parse('2026-07-21T00:00:00Z'),
  endMs: Date.parse('2026-07-21T02:00:00Z'),
}

function hourlyPayload() {
  return {
    hourly: {
      time: ['2026-07-21T00:00', '2026-07-21T01:00'],
      precipitation: [0.1, 0.2],
      temperature_2m: [50.0, 52.0],
      wind_speed_10m: [5.0, 7.0],
    },
  }
}

function jsonResponse(body: unknown): Response {
  return { ok: true, status: 200, json: async () => body } as unknown as Response
}

afterEach(() => {
  vi.unstubAllGlobals()
})

describe('fetchWeather', () => {
  it('normalizes the single-location object payload to one result', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse(hourlyPayload())))
    const out = await fetchWeather(
      [{ latitude: 47.5, longitude: -121.9 }],
      WINDOW.startMs,
      WINDOW.endMs,
    )
    expect(out).toHaveLength(1)
    expect(out[0]?.precip_total_in).toBe(0.3)
    expect(out[0]?.series?.times).toHaveLength(2)
  })

  it('throws OpenMeteoUnreachable on HTTP errors (the fallback trigger)', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({ ok: false, status: 429, json: async () => ({}) })),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs),
    ).rejects.toBeInstanceOf(OpenMeteoUnreachable)
  })

  it('wraps network-level rejections too — the corporate-proxy case', async () => {
    // fetch rejects with a TypeError when the request never completes
    // (offline, DNS, blocked CORS). That must read as "unreachable", not
    // crash through as an unclassified error.
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new TypeError('Failed to fetch')
      }),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs),
    ).rejects.toBeInstanceOf(OpenMeteoUnreachable)
  })

  it('lets a user cancel pass through untranslated', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new DOMException('The user aborted a request.', 'AbortError')
      }),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs),
    ).rejects.toMatchObject({ name: 'AbortError' })
  })

  it('throws on a miscounted response instead of misaligning rows', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => jsonResponse([hourlyPayload(), hourlyPayload()])),
    )
    await expect(
      fetchWeather([{ latitude: 0, longitude: 0 }], WINDOW.startMs, WINDOW.endMs),
    ).rejects.toBeInstanceOf(OpenMeteoUnreachable)
  })

  it('reports batch progress across chunks', async () => {
    const dests = Array.from({ length: 60 }, (_, i) => ({
      latitude: i,
      longitude: i,
    }))
    vi.stubGlobal(
      'fetch',
      vi.fn(async (url: string) => {
        const count = new URL(url).searchParams.get('latitude')!.split(',').length
        return jsonResponse(Array.from({ length: count }, () => hourlyPayload()))
      }),
    )
    const seen: Array<[number, number]> = []
    await fetchWeather(dests, WINDOW.startMs, WINDOW.endMs, {
      onProgress: (processed, total) => seen.push([processed, total]),
    })
    // Two chunks (50 + 10) completing in either order: the processed counter
    // accumulates monotonically and ends at the full total.
    expect(seen).toHaveLength(2)
    expect(seen.every(([, total]) => total === 60)).toBe(true)
    expect(seen[0][0]).toBeLessThan(seen[1][0])
    expect(seen[1][0]).toBe(60)
  })
})

describe('fetchAqi', () => {
  it('degrades any failure to nulls instead of throwing', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({ ok: false, status: 500, json: async () => ({}) })),
    )
    const out = await fetchAqi(
      [{ latitude: 0, longitude: 0 }],
      WINDOW.startMs,
      WINDOW.endMs,
    )
    expect(out).toEqual([null])
  })

  it('degrades a miscounted response to nulls', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse([{}, {}])))
    const out = await fetchAqi(
      [{ latitude: 0, longitude: 0 }],
      WINDOW.startMs,
      WINDOW.endMs,
    )
    expect(out).toEqual([null])
  })

  it('skips the fetch entirely when the window starts past the horizon', async () => {
    const fetchSpy = vi.fn()
    vi.stubGlobal('fetch', fetchSpy)
    const now = Date.parse('2026-07-01T00:00:00Z')
    const out = await fetchAqi(
      [{ latitude: 0, longitude: 0 }],
      Date.parse('2026-07-20T00:00:00Z'),
      Date.parse('2026-07-21T00:00:00Z'),
      { nowMs: now },
    )
    expect(out).toEqual([null])
    expect(fetchSpy).not.toHaveBeenCalled()
  })

  it('clamps the requested end date to the ~5-day horizon', async () => {
    let requested: string | null = null
    vi.stubGlobal(
      'fetch',
      vi.fn(async (url: string) => {
        requested = new URL(url).searchParams.get('end_date')
        return jsonResponse({ hourly: { time: [], us_aqi: [] } })
      }),
    )
    const now = Date.parse('2026-07-21T00:00:00Z')
    await fetchAqi(
      [{ latitude: 0, longitude: 0 }],
      now,
      now + 15 * 86_400_000,
      { nowMs: now },
    )
    expect(requested).toBe('2026-07-26')
  })
})
