import { describe, expect, it } from 'vitest'
import {
  aqiMetrics,
  aqiSeries,
  parseTs,
  roundHalfEven,
  tempAtElevation,
  weatherMetrics,
  weatherSeries,
} from './openMeteoAggregate'
import vectors from '../../../backend/tests/data/weather_vectors.json'
// `?raw` gives a file's text without executing it, the drift-guard idiom
// `styles.test.ts` and `metrics.test.ts` use.
import aggregateSource from './openMeteoAggregate.ts?raw'
// The Vitest container mounts the repository root, so the backend's half is on
// disk here the way the vectors are.
import pythonSource from '../../../backend/app/services/aggregation.py?raw'


// ── The shared-vector contract ─────────────────────────────────────────────
// weather_vectors.json is generated by the backend reference implementation
// (backend/scripts/generate_weather_vectors.py) and read from where that
// script writes it, so there is one file rather than two copies to hold
// together. These tests are the frontend half of the contract: the TypeScript
// port must reproduce every expectation byte-for-byte.

type VectorCase = {
  name: string
  window: { start: string; end: string }
  payload: never
  elevation_ft?: number
  expected_metrics: unknown
  expected_series: unknown
}

function windowMs(c: VectorCase): [number, number] {
  return [parseTs(c.window.start)!, parseTs(c.window.end)!]
}

describe('weather vectors', () => {
  for (const c of vectors.weather as unknown as VectorCase[]) {
    it(c.name, () => {
      const [startMs, endMs] = windowMs(c)
      const elevationFt = c.elevation_ft ?? null
      expect(weatherMetrics(c.payload, startMs, endMs, elevationFt)).toEqual(
        c.expected_metrics,
      )
      expect(weatherSeries(c.payload, startMs, endMs, elevationFt)).toEqual(
        c.expected_series,
      )
    })
  }
})

describe('aqi vectors', () => {
  for (const c of vectors.aqi as unknown as VectorCase[]) {
    it(c.name, () => {
      const [startMs, endMs] = windowMs(c)
      expect(aqiMetrics(c.payload, startMs, endMs)).toEqual(c.expected_metrics)
      expect(aqiSeries(c.payload, startMs, endMs)).toEqual(c.expected_series)
    })
  }
})

// ── Parity primitives ──────────────────────────────────────────────────────

describe('roundHalfEven', () => {
  it('rounds halves to the even neighbor, like Python round()', () => {
    expect(roundHalfEven(80.5, 0)).toBe(80)
    expect(roundHalfEven(81.5, 0)).toBe(82)
    expect(roundHalfEven(50.25, 1)).toBe(50.2)
    expect(roundHalfEven(50.75, 1)).toBe(50.8)
    expect(roundHalfEven(0.03125, 4)).toBe(0.0312)
  })

  it('rounds non-halves normally', () => {
    expect(roundHalfEven(1.24, 1)).toBe(1.2)
    expect(roundHalfEven(1.26, 1)).toBe(1.3)
  })
})

describe('parseTs', () => {
  it('reads naive Open-Meteo stamps as UTC, never local time', () => {
    // Without the Z re-stamp, environments west of UTC would shift this by
    // the local offset — the exact trap the port exists to avoid.
    expect(parseTs('2026-07-21T00:00')).toBe(Date.parse('2026-07-21T00:00:00Z'))
  })

  it('reads a number as unixtime seconds', () => {
    // What every request this module sends now asks for (#337, finding 4):
    // `timeformat=unixtime`, so the wire carries whole seconds. The string arm
    // above stays because `weather_vectors.json` feeds ISO stamps through the
    // same function.
    expect(parseTs(1784592000)).toBe(Date.parse('2026-07-21T00:00:00Z'))
    expect(parseTs(0)).toBe(0)
  })

  it('degrades garbage to null like the backend parser', () => {
    expect(parseTs('not-a-time')).toBeNull()
    expect(parseTs(Number.NaN)).toBeNull()
    expect(parseTs(Number.POSITIVE_INFINITY)).toBeNull()
    expect(parseTs(null)).toBeNull()
    expect(parseTs({})).toBeNull()
  })
})

// #443. The vectors pin this inside the aggregation; these read the function
// itself, because the rules that make it right are stated one at a time and a
// vector states them only as a number at the end.
describe('tempAtElevation', () => {
  // 925 / 850 / 700 / 600 / 500 hPa at their ISA heights in meters. Elevations
  // below are in feet, as destinations carry them.
  const LEVELS = [55, 48, 38, 28, 14]

  // 8,000 ft is 2438.4 m, between 850 hPa (1457 m) and 700 hPa (3012 m). The
  // fraction is (2438.4 - 1457) / (3012 - 1457).
  it('interpolates between the two bracketing levels', () => {
    const f = (2438.4 - 1457) / (3012 - 1457)
    expect(tempAtElevation(25, 8000, LEVELS)).toBeCloseTo(48 + (38 - 48) * f, 10)
  })

  // The whole of what "no floor" means, and the one rule that differs from the
  // wind: a summit under an inversion is warmer than the free air, and the
  // reading has to say so rather than clamping to the surface value.
  it('reports free air colder than the surface reading', () => {
    expect(tempAtElevation(60, 8000, LEVELS)).toBeLessThan(60)
  })

  it('reports free air warmer than the surface reading', () => {
    expect(tempAtElevation(10, 8000, LEVELS)).toBeGreaterThan(10)
  })

  // A valley destination IS its own surface layer, so the 2 m value stands.
  // 2,500 ft is 762 m, the lowest level exactly, and the boundary is inclusive.
  it('keeps the surface reading at or below the lowest level', () => {
    expect(tempAtElevation(25, 2000, LEVELS)).toBe(25)
    expect(tempAtElevation(25, 762 / 0.3048, LEVELS)).toBe(25)
  })

  // Above the top level there is nothing to interpolate against, so the top
  // level stands rather than being extrapolated past.
  it('clamps to the top level above it', () => {
    expect(tempAtElevation(40, 20000, LEVELS)).toBe(14)
  })

  // Four gaps, one answer. The last is the archive, which accepts all five
  // levels and answers every hour null (measured 2026-09-16).
  it('falls back to the surface reading for every gap', () => {
    expect(tempAtElevation(25, null, LEVELS)).toBe(25)
    expect(tempAtElevation(25, undefined, LEVELS)).toBe(25)
    expect(tempAtElevation(25, 8000, [])).toBe(25)
    expect(tempAtElevation(25, 8000, [55, null, 38, 28, 14])).toBe(25)
    expect(tempAtElevation(25, 8000, [null, null, null, null, null])).toBe(25)
  })

  // Negatives are the ordinary winter case at these levels, and a port that
  // interpolated on magnitude would pass every test above and fail here.
  it('interpolates across zero', () => {
    const below = tempAtElevation(20, 17000, [55, 48, 38, 10, -20])
    expect(below).toBeGreaterThan(-20)
    expect(below).toBeLessThan(10)
  })
})


// ── One arithmetic, listed twice ───────────────────────────────────────────
//
// The vectors above pin what the two implementations compute. They cannot pin
// that a reviewer holding the two files side by side is reading the same
// function on each line, which is what the two modules exist for. So this
// reads both as text: every top-level function, in order, with the naming
// convention of each language taken out.
//
// A text test because it is a check across two artifacts in two languages.

// Helpers one language needs and the other does not. Python's `round` is
// already half-even, so it needs no `roundHalfEven`; the browser's stamps are
// epoch milliseconds from the start, so it has no zone to strip and nothing to
// convert.
const TS_ONLY = new Set(['roundHalfEven', 'tieBreak'])
const PYTHON_ONLY = new Set(['naive', 'epochMs'])
// The same function under a name each side chose for itself, keyed by the
// Python name with its convention taken out.
const PORT_NAME: Record<string, string> = {
  roundOrNone: 'roundOrNull',
  freezeToFt: 'freezeToFeet',
}

function camel(snake: string): string {
  return snake.replace(/^_+/, '').replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
}

function tsFunctions(): string[] {
  return [...aggregateSource.matchAll(/^(?:export )?function (\w+)/gm)]
    .map((m) => m[1])
    .filter((name) => !TS_ONLY.has(name))
}

function pythonFunctions(): string[] {
  return [...pythonSource.matchAll(/^def (\w+)\(/gm)]
    .map((m) => camel(m[1]))
    .filter((name) => !PYTHON_ONLY.has(name))
    .map((name) => PORT_NAME[name] ?? name)
}

describe('the two aggregation modules', () => {
  it('list the same functions in the same order', () => {
    expect(tsFunctions()).toEqual(pythonFunctions())
  })

  it('read the functions they claim to compare', () => {
    // A pattern that stopped matching would make the comparison above two
    // empty lists, which agree.
    expect(tsFunctions()).toContain('weatherMetrics')
    expect(tsFunctions()).toContain('aqiSeries')
    expect(pythonFunctions()).toContain('joinHours')
    expect(pythonFunctions().length).toBeGreaterThan(10)
  })

  it('carry no exception the other side does not', () => {
    // An entry left in a list after its function moved or was renamed would
    // excuse a difference nothing has.
    const tsAll = [...aggregateSource.matchAll(/^(?:export )?function (\w+)/gm)].map((m) => m[1])
    const pyAll = [...pythonSource.matchAll(/^def (\w+)\(/gm)].map((m) => camel(m[1]))
    for (const name of TS_ONLY) expect(tsAll).toContain(name)
    for (const name of PYTHON_ONLY) expect(pyAll).toContain(name)
    for (const [py, ts] of Object.entries(PORT_NAME)) {
      expect(pyAll).toContain(py)
      expect(tsAll).toContain(ts)
    }
  })
})
